# Generated by Django 5.0.1 on 2024-03-10 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companyCode",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="companyCode",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "companyCode",
                "verbose_name_plural": "companyCode",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paymentType",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="paymentType"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment List",
                "verbose_name_plural": "Payment List",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="CompanyName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companyName",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="companyName",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companyName_companyCode",
                        to="accounts.companycode",
                    ),
                ),
            ],
            options={
                "verbose_name": "companyCode",
                "verbose_name_plural": "companyCode",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="CommunityGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "communityGroup",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="communityGroup",
                    ),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communityGroup_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communityGroup_companyName",
                        to="accounts.companyname",
                    ),
                ),
            ],
            options={
                "verbose_name": "communityGroup",
                "verbose_name_plural": "communityGroup",
                "ordering": ("-communityGroup",),
            },
        ),
        migrations.CreateModel(
            name="AreaCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="country"
                    ),
                ),
                (
                    "zipCode",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="zipCode"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areaCode_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areaCode_companyName",
                        to="accounts.companyname",
                    ),
                ),
            ],
            options={
                "verbose_name": "country",
                "verbose_name_plural": "country",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "companyListNo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="companyListNo",
                    ),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
                (
                    "communityGroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_communityGroup",
                        to="accounts.communitygroup",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_country",
                        to="accounts.areacode",
                    ),
                ),
                (
                    "zipCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_zipCode",
                        to="accounts.areacode",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_payment",
                        to="accounts.payment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Company List",
                "ordering": ("-createdDay",),
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="firstName"
                    ),
                ),
                (
                    "familyName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="familyName"
                    ),
                ),
                (
                    "userName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="userName"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phoneNumber",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="phoneNumber",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "createdDay",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="createdDay"
                    ),
                ),
                (
                    "updateDay",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="updateDay"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "communityGroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customUser_communityGroup",
                        to="accounts.communitygroup",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customUser_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customUser_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customUser_payment",
                        to="accounts.payment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User List",
                "ordering": ("-createdDay",),
            },
        ),
    ]
