# Generated by Django 5.0.1 on 2024-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "companyListNo",
                    models.IntegerField(default=0, verbose_name="ceListNo"),
                ),
                (
                    "companyName",
                    models.IntegerField(default=0, verbose_name="ceListNo"),
                ),
                ("country", models.IntegerField(default=0, verbose_name="ceListNo")),
                ("zipCode", models.IntegerField(default=0, verbose_name="ceListNo")),
                (
                    "accountType",
                    models.IntegerField(default=0, verbose_name="ceListNo"),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
