# Generated by Django 5.0.1 on 2024-03-02 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "companyListNo",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="companyListNo",
                    ),
                ),
                (
                    "companyName",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="companyName",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="country"
                    ),
                ),
                (
                    "zipCode",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="zipCode"
                    ),
                ),
                (
                    "accountType",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="accountType",
                    ),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "companyCode",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="companyCode",
                    ),
                ),
                (
                    "companyName",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="companyName",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="country"
                    ),
                ),
                (
                    "zipCode",
                    models.EmailField(
                        blank=True, max_length=200, null=True, verbose_name="zipCode"
                    ),
                ),
                (
                    "accountType",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="accountType",
                    ),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "userName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="userName"
                    ),
                ),
                (
                    "firstName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="firstName"
                    ),
                ),
                (
                    "familyName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="familyName"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phoneNumber",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="phoneNumber",
                    ),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.payment",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_info",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.userinfo",
            ),
        ),
    ]
