# Generated by Django 5.0.1 on 2024-02-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("userName", models.IntegerField(default=0, verbose_name="userName")),
                ("firstName", models.IntegerField(default=0, verbose_name="firstName")),
                (
                    "familyName",
                    models.IntegerField(default=0, verbose_name="familyName"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="email")),
                (
                    "phoneNumber",
                    models.IntegerField(default=0, verbose_name="phoneNumber"),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="companylist",
            name="accountType",
            field=models.IntegerField(default=0, verbose_name="accountType"),
        ),
        migrations.AlterField(
            model_name="companylist",
            name="companyListNo",
            field=models.IntegerField(default=0, verbose_name="companyListNo"),
        ),
        migrations.AlterField(
            model_name="companylist",
            name="companyName",
            field=models.IntegerField(default=0, verbose_name="companyName"),
        ),
        migrations.AlterField(
            model_name="companylist",
            name="country",
            field=models.IntegerField(default=0, verbose_name="country"),
        ),
        migrations.AlterField(
            model_name="companylist",
            name="zipCode",
            field=models.IntegerField(default=0, verbose_name="zipCode"),
        ),
    ]
