# Generated by Django 5.0.1 on 2024-03-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyname",
            options={
                "ordering": ("id",),
                "verbose_name": "companyName",
                "verbose_name_plural": "companyName",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ("id",), "verbose_name_plural": "User List"},
        ),
    ]
