# Generated by Django 5.0.1 on 2024-03-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_payment",
                to="accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="payment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="payment"
            ),
        ),
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ("-createdDay",),
                "verbose_name_plural": "Company List",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ("-createdDay",), "verbose_name_plural": "User List"},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="company",
        ),
        migrations.AddField(
            model_name="company",
            name="communityGroup",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="communityGroup"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="communityGroup",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="communityGroup"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="companyName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_companyName",
                to="accounts.company",
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
