# Generated by Django 5.0.1 on 2024-03-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_payment_alter_company_payment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("freeUser", models.BooleanField(default=False)),
                ("lightUser", models.BooleanField(default=False)),
                ("middleUser", models.BooleanField(default=False)),
                ("specialUser", models.BooleanField(default=False)),
                ("premiumUser", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Payment List",
                "ordering": ("-premiumUser",),
            },
        ),
    ]
