# Generated by Django 5.0.1 on 2024-02-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userlist_alter_companylist_accounttype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "companyCode",
                    models.IntegerField(default=0, verbose_name="companyCode"),
                ),
                (
                    "companyName",
                    models.IntegerField(default=0, verbose_name="companyName"),
                ),
                ("country", models.IntegerField(default=0, verbose_name="country")),
                ("zipCode", models.EmailField(max_length=254, verbose_name="zipCode")),
                (
                    "accountType",
                    models.IntegerField(default=0, verbose_name="accountType"),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
