# Generated by Django 5.0.1 on 2024-03-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_payment_userinfo_customuser_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="companyCode",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="companyCode"
            ),
        ),
    ]
