# Generated by Django 5.0.1 on 2024-06-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycode",
            name="companyCode",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="companyCode",
            ),
        ),
    ]
