# Generated by Django 5.0.1 on 2024-02-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_paymentslist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompanyList",
            new_name="Company",
        ),
        migrations.RenameModel(
            old_name="PaymentsList",
            new_name="Payment",
        ),
        migrations.RenameModel(
            old_name="UserList",
            new_name="User",
        ),
    ]
