# Generated by Django 5.0.1 on 2024-03-09 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_payment",
                to="accounts.payment",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="companyName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customUser_companyName",
                to="accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customUser_payment",
                to="accounts.company",
            ),
        ),
    ]
