# Generated by Django 5.0.1 on 2024-02-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_companylist_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="accountType",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="accountType"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyListNo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="companyListNo"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="companyName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="companyName"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="country",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="zipCode",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="zipCode"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="accountType",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="accountType"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="companyCode",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="companyCode"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="companyName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="companyName"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="country",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="zipCode",
            field=models.EmailField(
                blank=True, max_length=200, null=True, verbose_name="zipCode"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="familyName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="familyName"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="firstName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="firstName"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="phoneNumber"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="userName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="userName"
            ),
        ),
    ]
