# Generated by Django 5.0.1 on 2024-03-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_alter_company_payment_alter_customuser_companyname_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="payment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="payment"
            ),
        ),
    ]
