# Generated by Django 5.0.1 on 2024-09-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plant",
            options={
                "ordering": ("plantName",),
                "verbose_name": "PlantName",
                "verbose_name_plural": "PlantName",
            },
        ),
        migrations.RemoveField(
            model_name="plant",
            name="plant",
        ),
        migrations.AddField(
            model_name="plant",
            name="plantName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="plantName"
            ),
        ),
    ]
