# Generated by Django 5.0.1 on 2024-09-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_plant_options_remove_plant_plant_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plant",
            options={
                "ordering": ("plant",),
                "verbose_name": "Plant",
                "verbose_name_plural": "Plant",
            },
        ),
        migrations.RemoveField(
            model_name="plant",
            name="plantName",
        ),
        migrations.AddField(
            model_name="plant",
            name="plant",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="plant"
            ),
        ),
    ]
