# Generated by Django 5.0.1 on 2024-03-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_company_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ("-paymentType",),
                "verbose_name_plural": "Payment List",
            },
        ),
        migrations.RemoveField(
            model_name="payment",
            name="freeUser",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="lightUser",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="middleUser",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="premiumUser",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="specialUser",
        ),
        migrations.AddField(
            model_name="payment",
            name="paymentType",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="paymentType"
            ),
        ),
    ]
