# Generated by Django 5.0.1 on 2024-03-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_payment_options_remove_payment_freeuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="slug",
        ),
    ]
