# Generated by Django 5.0.1 on 2024-03-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_payment_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="description"
            ),
        ),
    ]
