# Generated by Django 5.0.1 on 2024-03-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_payment_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ("-paymentType",),
                "verbose_name": "Payment List",
                "verbose_name_plural": "Payment List",
            },
        ),
    ]
