# Generated by Django 5.0.1 on 2024-03-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_payment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
