# Generated by Django 5.0.1 on 2024-03-09 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_company_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="slug",
        ),
    ]
