# Generated by Django 5.0.1 on 2024-03-09 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_remove_company_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customUser_payment",
                to="accounts.payment",
            ),
        ),
    ]
