# Generated by Django 5.0.1 on 2024-03-10 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("ceList", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpareParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="image"
                    ),
                ),
                (
                    "partsNo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="partsName"
                    ),
                ),
                (
                    "partsName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="partsName"
                    ),
                ),
                (
                    "partsModel",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="partsModel"
                    ),
                ),
                (
                    "serialNumber",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="serialNumber",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="category"
                    ),
                ),
                (
                    "bomCode",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="bomNo"
                    ),
                ),
                (
                    "partsCost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="partsCost",
                    ),
                ),
                (
                    "numberOf",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="numberOf"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="unit"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="location"
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="stock"
                    ),
                ),
                (
                    "partsDeliveryTime",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="partsDeliveryTime",
                    ),
                ),
                (
                    "partsDescription",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="partsDescription",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spareParts_companyCode",
                        to="accounts.company",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spareParts_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spareParts_equipment",
                        to="ceList.equipment",
                    ),
                ),
                (
                    "function",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spareParts_function",
                        to="ceList.function",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spareParts_plant",
                        to="ceList.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spare Parts List",
                "verbose_name_plural": "Spare Parts List",
                "ordering": ("partsName",),
            },
        ),
    ]
