# Generated by Django 5.0.1 on 2024-03-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="location"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="spareparts",
            name="classification",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="classification"
            ),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="inventoryTurnover",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="classification"
            ),
        ),
    ]
