# Generated by Django 5.0.1 on 2024-03-09 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customuser_payment"),
        ("ceList", "0007_alter_celist_options_remove_celist_celistno_and_more"),
        ("spareParts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spareparts",
            options={
                "ordering": ("partsName",),
                "verbose_name": "Spare Parts List",
                "verbose_name_plural": "Spare Parts List",
            },
        ),
        migrations.RenameField(
            model_name="spareparts",
            old_name="bomNo",
            new_name="bomCode",
        ),
        migrations.AddField(
            model_name="spareparts",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="equipment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="equipment"
            ),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="function",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="function"
            ),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="partsNo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="partsName"
            ),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ceList.celist",
            ),
        ),
    ]
