# Generated by Django 5.0.1 on 2024-03-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0002_rename_bomno_spareparts_bomcode_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spareparts",
            options={
                "ordering": ("partsName",),
                "verbose_name": "Spare Parts List",
                "verbose_name_plural": "Spare Parts List",
            },
        ),
    ]
