# Generated by Django 5.0.1 on 2024-03-13 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0004_alter_typeofpm_description"),
        ("spareParts", "0002_category_classification_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("category",),
                "verbose_name": "Category",
                "verbose_name_plural": "Category",
            },
        ),
        migrations.AlterModelOptions(
            name="classification",
            options={
                "ordering": ("classification",),
                "verbose_name": "Classification",
                "verbose_name_plural": "Classification",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "ordering": ("location",),
                "verbose_name": "Location",
                "verbose_name_plural": "Location",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="category"
            ),
        ),
        migrations.AddField(
            model_name="classification",
            name="description",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="locationNo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="locationNo"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="category"
            ),
        ),
        migrations.AlterField(
            model_name="classification",
            name="classification",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="classification"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spareParts_category",
                to="spareParts.category",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spareParts_classification",
                to="spareParts.classification",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spareParts_location",
                to="spareParts.location",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="machineName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spareParts_machineName",
                to="ceList.machine",
            ),
        ),
    ]
