# Generated by Django 5.0.1 on 2024-03-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0002_alter_spareparts_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="image"
            ),
        ),
    ]
