# Generated by Django 5.0.1 on 2024-03-13 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        (
            "spareParts",
            "0003_alter_category_options_alter_classification_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_companyCode",
                to="accounts.company",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="companyName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_companyName",
                to="accounts.companyname",
            ),
        ),
    ]
