# Generated by Django 5.0.1 on 2024-03-13 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("spareParts", "0004_location_companycode_location_companyname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="locationNo",
        ),
        migrations.AddField(
            model_name="location",
            name="location_Id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="location_id"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spareParts_companyCode",
                to="accounts.companycode",
            ),
        ),
    ]
