# Generated by Django 5.0.1 on 2024-03-20 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("ceList", "0007_alter_celist_machinename_and_more"),
        ("spareParts", "0006_remove_spareparts_equipment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="category",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="category"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="classification",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="classification"
            ),
        ),
        migrations.RemoveField(
            model_name="location",
            name="companyCode",
        ),
        migrations.RemoveField(
            model_name="location",
            name="companyName",
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="location"
            ),
        ),
        migrations.RemoveField(
            model_name="sparepartsalertnextmonth",
            name="companyCode",
        ),
        migrations.RemoveField(
            model_name="sparepartsalertnextmonth",
            name="companyName",
        ),
        migrations.AddField(
            model_name="spareparts",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spareParts_equipment",
                to="ceList.equipment",
            ),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="machineName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spareParts_machineName",
                to="ceList.celist",
            ),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="order",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="order"
            ),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="orderSituation",
            field=models.BooleanField(default=False, verbose_name="orderSituation"),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spareParts_plant",
                to="accounts.plant",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="inventoryTurnover",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="inventoryTurnover"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsModel",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="partsModel"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsName",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="partsName"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsNo",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="partsName"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="serialNumber",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="serialNumber"
            ),
        ),
        migrations.CreateModel(
            name="BomList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maxPartsDeliveryTimeInBom",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="maxPartsDeliveryTimeInBom",
                    ),
                ),
                (
                    "bomCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bomList_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "bomCost",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bomList_companyName",
                        to="accounts.companyname",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bom List",
                "verbose_name_plural": "Bom List",
                "ordering": ("bomCode",),
            },
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Classification",
        ),
        migrations.DeleteModel(
            name="location",
        ),
        migrations.DeleteModel(
            name="SparePartsAlertNextMonth",
        ),
    ]
