# Generated by Django 5.0.1 on 2024-03-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0007_alter_spareparts_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spareparts",
            old_name="order",
            new_name="orderAlert",
        ),
    ]
