# Generated by Django 5.0.1 on 2024-03-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0008_rename_order_spareparts_orderalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="spareparts",
            name="taskCode",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="taskCode"
            ),
        ),
    ]
