# Generated by Django 5.0.1 on 2024-03-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0009_spareparts_taskcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="partsNo",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="partsNo"
            ),
        ),
    ]
