# Generated by Django 5.0.1 on 2024-03-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0010_alter_spareparts_partsno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="numberOf",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="numberOf"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="partsCost",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsDeliveryTime",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="partsDeliveryTime"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="unit",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="unit"
            ),
        ),
    ]
