# Generated by Django 5.0.1 on 2024-03-25 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "spareParts",
            "0011_alter_spareparts_numberof_alter_spareparts_partscost_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomlist",
            name="bomCode",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="bomCode"
            ),
        ),
        migrations.AlterField(
            model_name="bomlist",
            name="bomCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="bomCost",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="bomCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spareParts_companyCode",
                to="spareParts.bomlist",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="classification",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="classification"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="inventoryTurnover",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="inventoryTurnover"
            ),
        ),
    ]
