# Generated by Django 5.0.1 on 2024-03-25 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0008_machine_alter_celist_machinename"),
        ("spareParts", "0012_alter_bomlist_bomcode_alter_bomlist_bomcost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="bomCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spareParts_bomCode",
                to="spareParts.bomlist",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="machineName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spareParts_machineName",
                to="ceList.machine",
            ),
        ),
    ]
