# Generated by Django 5.0.1 on 2024-04-01 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("spareParts", "0013_alter_spareparts_bomcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomlist",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bomList_companyCode",
                to="accounts.companycode",
            ),
        ),
    ]
