# Generated by Django 5.0.1 on 2024-04-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0016_spareparts_summedpartscost_alter_spareparts_numberof"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spareparts",
            name="inventoryTurnover",
        ),
        migrations.AddField(
            model_name="sparepartsmanagement",
            name="inventoryTurnover",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="inventoryTurnover"
            ),
        ),
    ]
