# Generated by Django 5.0.1 on 2024-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0017_remove_spareparts_inventoryturnover_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="bomCode",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="bomCode"
            ),
        ),
    ]
