# Generated by Django 5.0.1 on 2024-08-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0018_alter_spareparts_bomcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="companyName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="companyName"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="equipment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="equipment"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="machineName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="machineName"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="orderAlert",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="orderAlert"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="plant",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="plant"
            ),
        ),
    ]
