# Generated by Django 5.0.1 on 2024-08-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0019_alter_spareparts_companyname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="partsNo",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="partsNo",
            ),
        ),
    ]
