# Generated by Django 5.0.1 on 2024-09-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0020_alter_spareparts_partsno"),
    ]

    operations = [
        migrations.AddField(
            model_name="spareparts",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="manufacturer"
            ),
        ),
    ]
