# Generated by Django 5.0.1 on 2024-09-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0021_spareparts_manufacturer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spareparts",
            name="taskCode",
        ),
        migrations.AddField(
            model_name="spareparts",
            name="taskListNo",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="taskListNo"
            ),
        ),
    ]
