# Generated by Django 5.0.1 on 2024-09-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
        ("spareParts", "0022_remove_spareparts_taskcode_spareparts_tasklistno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spareParts_plant",
                to="accounts.plant",
            ),
        ),
    ]
