# Generated by Django 5.0.1 on 2024-09-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0024_alter_spareparts_plant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparepartsmanagement",
            name="plant",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="plant"
            ),
        ),
    ]
