# Generated by Django 4.1.3 on 2023-10-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_email", models.EmailField(max_length=254)),
                ("job_tittle", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                ("salary", models.PositiveBigIntegerField()),
                ("prefecture", models.CharField(max_length=100)),
                ("city", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
