# Generated by Django 5.0.1 on 2024-03-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterDataTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bomCost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="bomCost",
                    ),
                ),
                (
                    "maxPartsDeliveryTimeInBom",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="maxPartsDeliveryTimeInBom",
                    ),
                ),
                (
                    "levelSetValue",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="levelSetValue"
                    ),
                ),
                (
                    "mttr",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="mttr"
                    ),
                ),
                (
                    "possibilityOfProductionLv",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="possibilityOfProductionLv",
                    ),
                ),
                (
                    "impactForProduction",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="impactForProduction",
                    ),
                ),
                (
                    "probabilityOfFailure",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="probabilityOfFailure",
                    ),
                ),
                (
                    "assessment",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="assessment"
                    ),
                ),
                (
                    "rcaOrReplace",
                    models.BooleanField(default=False, verbose_name="rcaOrReplace"),
                ),
                (
                    "sparePartsOrAlternative",
                    models.BooleanField(
                        default=False, verbose_name="sparePartsOrAlternative"
                    ),
                ),
                (
                    "coveredFromTask",
                    models.BooleanField(default=False, verbose_name="coveredFromTask"),
                ),
                ("twoways", models.BooleanField(default=False, verbose_name="twoways")),
                (
                    "ceDescription",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="ceDescription",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="junctiontable",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="junctiontable",
            name="bomCode",
        ),
        migrations.RemoveField(
            model_name="junctiontable",
            name="taskCode",
        ),
        migrations.RemoveField(
            model_name="spareparts",
            name="bomCode",
        ),
    ]
