# Generated by Django 5.0.1 on 2024-03-07 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpareParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taskCode",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskCode"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="junctiontable",
            options={
                "verbose_name": "Junction Table",
                "verbose_name_plural": "Junction Tables",
            },
        ),
        migrations.AlterField(
            model_name="junctiontable",
            name="bomCode",
            field=models.ForeignKey(
                blank=True,
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spare_parts",
                to="junctionTable.spareparts",
            ),
        ),
        migrations.AddField(
            model_name="spareparts",
            name="bomCode",
            field=models.ManyToManyField(
                through="junctionTable.JunctionTable", to="junctionTable.tasklist"
            ),
        ),
        migrations.AlterField(
            model_name="junctiontable",
            name="taskCode",
            field=models.ForeignKey(
                blank=True,
                default=0,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="junctionTable.tasklist",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="junctiontable",
            unique_together={("taskCode", "bomCode")},
        ),
        migrations.RemoveField(
            model_name="junctiontable",
            name="mostRecentBomCost",
        ),
        migrations.RemoveField(
            model_name="junctiontable",
            name="mostRecentPM",
        ),
    ]
