# Generated by Django 5.0.1 on 2024-03-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="junctiontable",
            name="totalCost",
        ),
    ]
