# Generated by Django 5.0.1 on 2024-03-07 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "junctionTable",
            "0002_spareparts_tasklist_alter_junctiontable_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="junctiontable",
            name="bomCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spare_parts",
                to="junctionTable.spareparts",
            ),
        ),
        migrations.AlterField(
            model_name="junctiontable",
            name="taskCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="junctionTable.tasklist",
            ),
        ),
    ]
