# Generated by Django 5.0.1 on 2024-03-09 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0003_alter_junctiontable_bomcode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="junctiontable",
            name="slug",
        ),
    ]
