# Generated by Django 5.0.1 on 2024-04-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("ceList", "0009_rename_celist_id_celist_celistno"),
        ("junctionTable", "0003_masterdatatable_countofpm02_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celistandtask",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ceListAndTask_equipment",
                to="ceList.equipment",
            ),
        ),
        migrations.AlterField(
            model_name="celistandtask",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ceListAndTask_machine",
                to="ceList.machine",
            ),
        ),
        migrations.CreateModel(
            name="BadActorManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badActor",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="badActor"
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badActorManagement_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badActorManagement_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badActorManagement_equipment",
                        to="ceList.equipment",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badActorManagement_machine",
                        to="ceList.machine",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badActorManagement_plant",
                        to="accounts.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "BadActorManagement",
                "verbose_name_plural": "BadActorManagement",
                "ordering": ("companyCode",),
            },
        ),
    ]
