# Generated by Django 5.0.1 on 2024-03-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0004_remove_masterdatatable_celist_id_and_more"),
        (
            "taskList",
            "0009_tasklistpm02_tasklistpm03_tasklistpm04_tasklistpm05_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="masterdatatable",
            name="taskPM02",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_taskPM02",
                to="taskList.tasklistpm02",
            ),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="taskPM03",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_taskPM03",
                to="taskList.tasklistpm03",
            ),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="taskPM04",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_taskPM04",
                to="taskList.tasklistpm04",
            ),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="taskPM05",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_taskPM05",
                to="taskList.tasklistpm05",
            ),
        ),
    ]
