# Generated by Django 5.0.1 on 2024-04-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0004_alter_celistandtask_equipment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badactormanagement",
            options={
                "ordering": ("companyCode",),
                "verbose_name": "Bad Actor Management",
                "verbose_name_plural": "Bad Actor Management",
            },
        ),
    ]
