# Generated by Django 5.0.1 on 2024-03-22 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "junctionTable",
            "0005_masterdatatable_taskpm02_masterdatatable_taskpm03_and_more",
        ),
        ("spareParts", "0007_alter_spareparts_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="thisYear"
            ),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear10ago",
            field=models.BooleanField(default=False, verbose_name="thisYear10ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear10later",
            field=models.BooleanField(default=False, verbose_name="thisYear10later"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear1ago",
            field=models.BooleanField(default=False, verbose_name="thisYear1ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear1later",
            field=models.BooleanField(default=False, verbose_name="thisYear1later"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear2ago",
            field=models.BooleanField(default=False, verbose_name="thisYear2ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear2later",
            field=models.BooleanField(default=False, verbose_name="thisYear2later"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear3ago",
            field=models.BooleanField(default=False, verbose_name="thisYear3ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear3later",
            field=models.BooleanField(default=False, verbose_name="thisYear3later"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear4ago",
            field=models.BooleanField(default=False, verbose_name="thisYear4ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear4later",
            field=models.BooleanField(default=False, verbose_name="thisYear4later"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear5ago",
            field=models.BooleanField(default=False, verbose_name="thisYear5ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear5later",
            field=models.BooleanField(default=False, verbose_name="thisYear5later"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear6ago",
            field=models.BooleanField(default=False, verbose_name="thisYear6ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear6later",
            field=models.BooleanField(default=False, verbose_name="thisYear6later"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear7ago",
            field=models.BooleanField(default=False, verbose_name="thisYear7ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear7later",
            field=models.BooleanField(default=False, verbose_name="thisYear7later"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear8ago",
            field=models.BooleanField(default=False, verbose_name="thisYear8ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear8later",
            field=models.BooleanField(default=False, verbose_name="thisYear8later"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear9ago",
            field=models.BooleanField(default=False, verbose_name="thisYear9ago"),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="thisYear9later",
            field=models.BooleanField(default=False, verbose_name="thisYear9later"),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="bomCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_bomList",
                to="spareParts.bomlist",
            ),
        ),
    ]
