# Generated by Django 5.0.1 on 2024-03-26 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "junctionTable",
            "0007_masterdatatable_celistno_masterdatatable_bomstock_and_more",
        ),
        ("taskList", "0018_remove_tasklistpm02_countofpm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterdatatable",
            name="typicalSituation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_typicalSituation",
                to="taskList.typicaltasklist",
            ),
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="typicalTaskCost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_typicalTaskCost",
                to="taskList.typicaltasklist",
            ),
        ),
    ]
