# Generated by Django 5.0.1 on 2024-03-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0008_masterdatatable_typicalsituation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="masterdatatable",
            options={
                "ordering": ("ceListNo",),
                "verbose_name": "Master Data Table",
                "verbose_name_plural": "Master Data Table",
            },
        ),
        migrations.RenameField(
            model_name="masterdatatable",
            old_name="CeListNo",
            new_name="ceListNo",
        ),
    ]
