# Generated by Django 4.2.6 on 2024-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0008_remove_eventyearppm_ppm10latercost_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventyearppm",
            name="companyName",
        ),
        migrations.RemoveField(
            model_name="eventyearppm",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="eventyearppm",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="eventyearppm",
            name="plant",
        ),
        migrations.AlterField(
            model_name="eventyearppm",
            name="companyCode",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="companyCode"
            ),
        ),
    ]
