# Generated by Django 5.0.1 on 2024-03-26 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0009_alter_masterdatatable_options_and_more"),
        ("spareParts", "0013_alter_spareparts_bomcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdatatable",
            name="maxPartsDeliveryTimeInBom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_maxPartsDeliveryTimeInBom",
                to="spareParts.bomlist",
            ),
        ),
    ]
