# Generated by Django 5.0.1 on 2024-03-26 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0010_alter_masterdatatable_maxpartsdeliverytimeinbom"),
        ("taskList", "0018_remove_tasklistpm02_countofpm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdatatable",
            name="countOfPM03",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_countOfPM03",
                to="taskList.tasklistpm03",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="countOfPM04",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_countOfPM04",
                to="taskList.tasklistpm04",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="countOfPM05",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_countOfPM05",
                to="taskList.tasklistpm05",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="laborCostOfPM03",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_laborCostOfPM03",
                to="taskList.tasklistpm03",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="laborCostOfPM04",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_laborCostOfPM04",
                to="taskList.tasklistpm04",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="laborCostOfPM05",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_laborCostOfPM05",
                to="taskList.tasklistpm05",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="latestPM03",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_latestPM03",
                to="taskList.tasklistpm03",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="latestPM04",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_latestPM04",
                to="taskList.tasklistpm04",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="latestPM05",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_latestPM05",
                to="taskList.tasklistpm05",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="thisYear",
            field=models.BooleanField(default=False, verbose_name="thisYear"),
        ),
    ]
