# Generated by Django 4.2.6 on 2024-04-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0011_alter_eventyearppm_ppm0yearcost_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventYearAPM",
        ),
    ]
