# Generated by Django 5.0.1 on 2024-03-31 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0009_rename_celist_id_celist_celistno"),
        ("junctionTable", "0011_alter_masterdatatable_countofpm03_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdatatable",
            name="machineName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="masterDataTable_machineName",
                to="ceList.machine",
            ),
        ),
    ]
