# Generated by Django 5.0.1 on 2024-04-06 06:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("junctionTable", "0013_alter_masterdatatable_countofpm02_and_more"),
        ("spareParts", "0014_bomlist_companycode"),
        ("taskList", "0021_delete_tasklistpm02_delete_tasklistpm03_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nextMonthTaskAlert",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="nextMonthAlert",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertSchedule_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertSchedule_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertSchedule_plant",
                        to="accounts.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlertSchedule",
                "verbose_name_plural": "AlertSchedule",
                "ordering": ("companyCode",),
            },
        ),
        migrations.CreateModel(
            name="BomAndTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bomAndTaskSet",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="bomAndTaskSet",
                    ),
                ),
                (
                    "bomAndTaskSetCost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="bomAndTaskSetCost",
                    ),
                ),
                (
                    "bomCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bomAndTask_bomCode",
                        to="spareParts.bomlist",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bomAndTask_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bomAndTask_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bomAndTask_plant",
                        to="accounts.plant",
                    ),
                ),
                (
                    "taskCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bomAndTask_taskCode",
                        to="taskList.tasklist",
                    ),
                ),
            ],
            options={
                "verbose_name": "BomAndTask",
                "verbose_name_plural": "BomAndTask",
                "ordering": ("bomCode",),
            },
        ),
    ]
