# Generated by Django 4.2.6 on 2024-04-08 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("spareParts", "0014_bomlist_companycode"),
        ("junctionTable", "0014_alertschedule_bomandtask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertschedule",
            name="nextMonthTaskAlert",
        ),
        migrations.AddField(
            model_name="alertschedule",
            name="deliveryTime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertSchedule_deliveryTime",
                to="spareParts.bomlist",
            ),
        ),
        migrations.AddField(
            model_name="alertschedule",
            name="eventDate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertSchedule_eventDate",
                to="spareParts.bomlist",
            ),
        ),
        migrations.AddField(
            model_name="alertschedule",
            name="orderAlertDate",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="orderAlertDate"
            ),
        ),
        migrations.AddField(
            model_name="alertschedule",
            name="partsName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertSchedule_partsName",
                to="spareParts.bomlist",
            ),
        ),
        migrations.AddField(
            model_name="alertschedule",
            name="safetyRate",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="safetyRate"
            ),
        ),
    ]
