# Generated by Django 5.0.1 on 2024-06-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("ceList", "0011_riskmatriximpact"),
        ("junctionTable", "0014_gapofrepairingcost"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="masterdatatable",
            unique_together={("companyCode", "ceListNo")},
        ),
    ]
