# Generated by Django 5.0.1 on 2024-07-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0015_alter_masterdatatable_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="masterdatatable",
            name="possibilityOfProductionLv",
        ),
        migrations.AddField(
            model_name="masterdatatable",
            name="possibilityOfContinuousProduction",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="possibilityOfContinuousProduction",
            ),
        ),
    ]
