# Generated by Django 5.0.1 on 2024-04-08 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0015_remove_alertschedule_nextmonthtaskalert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertschedule",
            name="deliveryTime",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="deliveryTime",
            ),
        ),
        migrations.AlterField(
            model_name="alertschedule",
            name="eventDate",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="eventDate",
            ),
        ),
        migrations.AlterField(
            model_name="alertschedule",
            name="orderAlertDate",
            field=models.DateField(
                blank=True, default=0, null=True, verbose_name="orderAlertDate"
            ),
        ),
    ]
