# Generated by Django 5.0.1 on 2024-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0016_alter_alertschedule_deliverytime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertschedule",
            name="deliveryTime",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="deliveryTime"
            ),
        ),
        migrations.AlterField(
            model_name="alertschedule",
            name="orderAlertDate",
            field=models.DateField(
                blank=True, null=True, verbose_name="orderAlertDate"
            ),
        ),
    ]
