# Generated by Django 5.0.1 on 2024-07-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "junctionTable",
            "0016_remove_masterdatatable_possibilityofproductionlv_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdatatable",
            name="bomStock",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="bomStock"
            ),
        ),
    ]
