# Generated by Django 5.0.1 on 2024-04-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("junctionTable", "0017_alter_alertschedule_deliverytime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertschedule",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertSchedule_areaCode",
                to="accounts.areacode",
            ),
        ),
    ]
