# Generated by Django 5.0.1 on 2024-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0017_alter_masterdatatable_bomstock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdatatable",
            name="coveredFromTask",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="coveredFromTask"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="rcaOrReplace",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="rcaOrReplace"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="sparePartsOrAlternative",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="sparePartsOrAlternative",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="twoways",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="twoways"
            ),
        ),
    ]
