# Generated by Django 5.0.1 on 2024-04-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0018_alertschedule_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AlertSchedule",
        ),
    ]
