# Generated by Django 5.0.1 on 2024-08-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0018_alter_masterdatatable_coveredfromtask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdatatable",
            name="levelSetValue",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="levelSetValue"
            ),
        ),
    ]
