# Generated by Django 5.0.1 on 2024-08-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0019_alter_masterdatatable_levelsetvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterdatatable",
            name="bomCode",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="bomCode"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="bomCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="bomCost",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="ceListNo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ceListNo"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="companyName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="companyName"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="countOfPM02",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM02"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="countOfPM03",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM03"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="countOfPM04",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM04"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="countOfPM05",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM05"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="equipment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="equipment"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="laborCostOfPM02",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="laborCostOfPM02",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="laborCostOfPM03",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="laborCostOfPM03",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="laborCostOfPM04",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="laborCostOfPM04",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="laborCostOfPM05",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="laborCostOfPM05",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="latestPM02",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM02"),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="latestPM03",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM03"),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="latestPM04",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM04"),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="latestPM05",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM05"),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="machineName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="machineName"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="maxPartsDeliveryTimeInBom",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="maxPartsDeliveryTimeInBom",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="multiTask",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="multiTask"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="plant",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="plant"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="taskPM02",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskPM02"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="taskPM03",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskPM03"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="taskPM04",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskPM04"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="taskPM05",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskPM05"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="totalCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="totalCost",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="typicalConstPeriod",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="typicalConstPeriod"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="typicalNextEventDate",
            field=models.DateField(
                blank=True, null=True, verbose_name="typicalNextEventDate"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="typicalSituation",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="typicalSituation"
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="typicalTaskCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="typicalTaskCost",
            ),
        ),
        migrations.AlterField(
            model_name="masterdatatable",
            name="typicalTaskName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="typicalTaskName"
            ),
        ),
    ]
