# Generated by Django 5.0.1 on 2024-09-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0022_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typical_task_name", models.CharField(max_length=100)),
                ("plant", models.CharField(max_length=100)),
                ("equipment", models.CharField(max_length=100)),
                ("machine_name", models.CharField(max_length=100)),
                ("typical_latest_date", models.DateField()),
                ("multi_tasking", models.BooleanField()),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("task_of_period", models.IntegerField()),
                ("typical_next_event_date", models.DateField()),
                ("typical_situation", models.CharField(max_length=100)),
            ],
        ),
    ]
