# Generated by Django 5.0.1 on 2024-09-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0023_basesimulation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BaseSimulation",
        ),
    ]
