# Generated by Django 5.0.1 on 2024-10-06 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0024_delete_basesimulation"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Schedule",
            new_name="ScheduleForGantt",
        ),
    ]
