# Generated by Django 5.0.1 on 2024-10-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0025_rename_schedule_scheduleforgantt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleForCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="eventTitle")),
                (
                    "eventType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("work order", "Work Order"),
                            ("daily report", "Daily Report"),
                            ("task", "Task"),
                            ("failure date", "Failure Date"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="eventType",
                    ),
                ),
                ("startDatetime", models.DateTimeField(verbose_name="startDate&Time")),
                ("endDatetime", models.DateTimeField(verbose_name="endDate&Time")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="eventDescription"
                    ),
                ),
            ],
            options={
                "ordering": ["startDatetime"],
            },
        ),
    ]
