# Generated by Django 5.0.1 on 2024-10-06 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_plant_options_remove_plant_plantname_and_more"),
        ("junctionTable", "0026_scheduleforcalendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleforcalendar",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduleForCalendar_companyCode",
                to="accounts.companycode",
            ),
        ),
    ]
