# Generated by Django 5.0.1 on 2024-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0027_scheduleforcalendar_companycode"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleforcalendar",
            name="eventDataNo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
