# Generated by Django 5.0.1 on 2024-10-06 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_plant_options_remove_plant_plantname_and_more"),
        ("junctionTable", "0028_scheduleforcalendar_eventdatano"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheduleforgantt",
            old_name="name",
            new_name="taskName",
        ),
        migrations.AddField(
            model_name="scheduleforgantt",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scheduleForGantt_companyCode",
                to="accounts.companycode",
            ),
        ),
    ]
