# Generated by Django 5.0.1 on 2024-10-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0029_rename_name_scheduleforgantt_taskname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scheduleforgantt",
            old_name="taskName",
            new_name="name",
        ),
    ]
