# Generated by Django 5.0.1 on 2024-10-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0030_rename_taskname_scheduleforgantt_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="celistandtask",
            name="equipment",
        ),
        migrations.RemoveField(
            model_name="celistandtask",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="celistandtask",
            name="plant",
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no10Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no10Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no10Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no10Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no10Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no10Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no10PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no10PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no10Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no10Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no11Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no11Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no11Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no11Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no11Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no11Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no11PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no11PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no11Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no11Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no12Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no12Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no12Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no12Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no12Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no12Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no12PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no12PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no12Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no12Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no13Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no13Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no13Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no13Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no13Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no13Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no13PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no13PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no13Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no13Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no14Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no14Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no14Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no14Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no14Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no14Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no14PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no14PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no14Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no14Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no15Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no15Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no15Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no15Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no15Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no15Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no15PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no15PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no15Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no15Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no16Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no16Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no16Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no16Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no16Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no16Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no16PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no16PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no16Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no16Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no17Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no17Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no17Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no17Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no17Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no17Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no17PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no17PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no17Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no17Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no18Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no18Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no18Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no18Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no18Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no18Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no18PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no18PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no18Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no18Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no19Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no19Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no19Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no19Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no19Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no19Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no19PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no19PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no19Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no19Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no1Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no1Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no1Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no1Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no1PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no1Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no20Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no20Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no20Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no20Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no20Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no20Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no20PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no20PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no20Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no20Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no2Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no2Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no2Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no2Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no2PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no2Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no3Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no3Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no3Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no3Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no3PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no3Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no4Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no4Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no4Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no4Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no4PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no4Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no5Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no5Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no5Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no5Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no5PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no5Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no6Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no6Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no6Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no6Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no6Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no6Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no6PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no6PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no6Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no6Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no7Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no7Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no7Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no7Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no7Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no7Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no7PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no7PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no7Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no7Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no8Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no8Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no8Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no8Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no8Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no8Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no8PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no8PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no8Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no8Plant"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no9Assessment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no9Assessment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no9Cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="no9Cost",
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no9Equipment",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no9Equipment"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no9PMType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no9PMType"
            ),
        ),
        migrations.AddField(
            model_name="celistandtask",
            name="no9Plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no9Plant"
            ),
        ),
    ]
