# Generated by Django 5.0.1 on 2024-05-01 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_plant"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "workOrderNo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "workOrderDesc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workOrder_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workOrder_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workOrder_plant",
                        to="accounts.plant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Work Order",
                "ordering": ("companyCode",),
            },
        ),
        migrations.CreateModel(
            name="WorkOrderManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workOrderManagement_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workOrderManagement_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workOrderManagement_plant",
                        to="accounts.plant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Work Order Management",
                "ordering": ("companyCode",),
            },
        ),
        migrations.CreateModel(
            name="WorkPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipment", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "workPermissionNo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "workPermissionDesc",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workPermission_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workPermission_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workPermission_plant",
                        to="accounts.plant",
                    ),
                ),
                (
                    "workOrderNo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workPermission_workOrder",
                        to="workOrder.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Work Permission",
                "ordering": ("workOrderNo",),
            },
        ),
    ]
