# Generated by Django 5.0.1 on 2024-08-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
        ("workOrder", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workorder",
            options={
                "ordering": ("companyCode",),
                "verbose_name_plural": "Work Orders",
            },
        ),
        migrations.AlterUniqueTogether(
            name="workorder",
            unique_together={("companyCode", "workOrderNo")},
        ),
        migrations.AddField(
            model_name="workorder",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="failureDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="failureDescription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="failureModes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="failureTypes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="workOrderDesc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="workorder",
            name="companyName",
        ),
    ]
