# Generated by Django 5.0.1 on 2024-08-23 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workOrder", "0002_alter_workorder_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="registrationDate",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
