# Generated by Django 5.0.1 on 2024-08-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workOrder", "0003_workorder_registrationdate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workpermission",
            options={
                "ordering": ("workOrderNo",),
                "verbose_name_plural": "Work Permissions",
            },
        ),
        migrations.RenameField(
            model_name="workpermission",
            old_name="workPermissionDesc",
            new_name="constructionPeriod",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="workPermissionNo",
        ),
        migrations.AddField(
            model_name="workpermission",
            name="personInCharge",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workpermission",
            name="taskName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
