# Generated by Django 5.0.1 on 2024-09-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workOrder", "0005_workpermission_approver_workpermission_breaker1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorder", models.CharField(max_length=100)),
                ("activity", models.TextField()),
                ("work_order", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "maintenance_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("maintenance_description", models.TextField(blank=True, null=True)),
                ("situation", models.TextField(blank=True, null=True)),
                ("cause", models.TextField(blank=True, null=True)),
                (
                    "spare_parts",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("handwritten_notes", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
            ],
        ),
    ]
