# Generated by Django 5.0.1 on 2024-09-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_plant_options_remove_plant_plantname_and_more"),
        ("workOrder", "0006_dailyreport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyreport",
            old_name="handwritten_notes",
            new_name="handwrittenNotes",
        ),
        migrations.RenameField(
            model_name="dailyreport",
            old_name="maintenance_description",
            new_name="maintenanceDescription",
        ),
        migrations.RenameField(
            model_name="dailyreport",
            old_name="maintenance_type",
            new_name="maintenanceType",
        ),
        migrations.RenameField(
            model_name="dailyreport",
            old_name="spare_parts",
            new_name="spareParts",
        ),
        migrations.RenameField(
            model_name="dailyreport",
            old_name="work_order",
            new_name="workOrder",
        ),
        migrations.AddField(
            model_name="dailyreport",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dailyReport_companyCode",
                to="accounts.companycode",
            ),
        ),
    ]
