# Generated by Django 5.0.1 on 2024-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workOrder",
            "0007_rename_handwritten_notes_dailyreport_handwrittennotes_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="handwrittenNotes",
            field=models.ImageField(
                blank=True, null=True, upload_to="handwritten_notes/"
            ),
        ),
    ]
