# Generated by Django 5.0.1 on 2024-09-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workOrder", "0008_alter_dailyreport_handwrittennotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="activity",
            field=models.TextField(blank=True, null=True),
        ),
    ]
