# Generated by Django 5.0.1 on 2024-09-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workOrder", "0009_alter_dailyreport_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="failureCauses",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="isUrgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workorder",
            name="picture1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="picture2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="pmTypes",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="requestType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="requestedBy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="situations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="workingBy",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="workingEndDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="workingStartDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
