# Generated by Django 5.0.1 on 2024-09-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workOrder", "0010_workorder_failurecauses_workorder_isurgent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorder",
            old_name="description",
            new_name="remark",
        ),
    ]
