# Generated by Django 5.0.1 on 2024-10-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workOrder", "0012_alter_workorder_plant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workpermission",
            name="breaker1",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="breaker2",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="breaker3",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="breaker4",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="breaker5",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="companyName",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="valve1",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="valve2",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="valve3",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="valve4",
        ),
        migrations.RemoveField(
            model_name="workpermission",
            name="valve5",
        ),
        migrations.AddField(
            model_name="workpermission",
            name="breakerApprovals",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="workpermission",
            name="breakerInputs",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="workpermission",
            name="valveApprovals",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="workpermission",
            name="valveInputs",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="workpermission",
            name="plant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
