# Generated by Django 5.0.1 on 2024-10-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workOrder", "0013_remove_workpermission_breaker1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workordermanagement",
            name="companyName",
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="breaker1_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="breaker2_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="breaker3_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="breaker4_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="breaker5_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="valve1_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="valve2_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="valve3_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="valve4_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="workordermanagement",
            name="valve5_approval_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="workordermanagement",
            name="plant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
