# Generated by Django 5.0.1 on 2024-10-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workOrder", "0014_remove_workordermanagement_companyname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workpermission",
            name="workPermissionNo",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
