# Generated by Django 5.0.1 on 2024-01-07 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("company_code", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
            ],
            options={
                "ordering": ("company_name",),
            },
        ),
        migrations.CreateModel(
            name="CeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_code", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("plant", models.CharField(max_length=200, verbose_name="プラント名")),
                ("equipment", models.CharField(max_length=200, verbose_name="設備名称")),
                ("function", models.CharField(max_length=200, verbose_name="機能場所")),
                (
                    "setting_value_impact",
                    models.CharField(max_length=200, verbose_name="impactへの設定値"),
                ),
                (
                    "construction_period",
                    models.CharField(max_length=200, verbose_name="工期"),
                ),
                (
                    "parts_deliver_date",
                    models.CharField(max_length=200, verbose_name="部品納期"),
                ),
                ("mttr", models.CharField(max_length=200, verbose_name="MTTR")),
                (
                    "number_pm02",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="PM02回数"
                    ),
                ),
                (
                    "latest_pm02",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="直近のPM02"
                    ),
                ),
                (
                    "number_pm03",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="PM03回数"
                    ),
                ),
                (
                    "latest_pm03",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="直剣のPM03"
                    ),
                ),
                (
                    "number_pm04",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="PM04回数"
                    ),
                ),
                (
                    "latest_pm04",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="直近のPM04"
                    ),
                ),
                (
                    "impact_production",
                    models.CharField(max_length=200, verbose_name="生産へのimpact"),
                ),
                (
                    "possibility_of_failure",
                    models.CharField(max_length=200, verbose_name="故障の可能性"),
                ),
                ("assessment", models.CharField(max_length=200, verbose_name="評価")),
                (
                    "task_pm02",
                    models.CharField(max_length=200, verbose_name="PM02タスク名称"),
                ),
                (
                    "cost_of_task",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="推定コスト"
                    ),
                ),
                ("period_of_task", models.CharField(max_length=200, verbose_name="周期")),
                ("next_event", models.CharField(max_length=200, verbose_name="次回の発生日")),
                (
                    "situation_for_pm02",
                    models.CharField(max_length=200, verbose_name="周期超過の有無"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="celist",
                        to="celist.company",
                    ),
                ),
            ],
        ),
    ]
