# Generated by Django 5.0.1 on 2024-02-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "ceListNo",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="ceListNo"
                    ),
                ),
                (
                    "companyCode",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="companyCode",
                    ),
                ),
                (
                    "plant",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="plant"
                    ),
                ),
                (
                    "locationNo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="locationNo"
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="function"
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="equipment"
                    ),
                ),
                (
                    "bomNo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="bomNo"
                    ),
                ),
                (
                    "totalBomCost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="totalBomCost",
                    ),
                ),
                (
                    "valueImpact",
                    models.CharField(max_length=200, verbose_name="valueImpact"),
                ),
                (
                    "constructionPeriod",
                    models.DurationField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="constructionPeriod",
                    ),
                ),
                (
                    "partsDeliveryTime",
                    models.DurationField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="partsDeliveryTime",
                    ),
                ),
                (
                    "mttr",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="mttr"
                    ),
                ),
                (
                    "countOfPM02",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="countOfPM02"
                    ),
                ),
                (
                    "latestPM02",
                    models.DateField(blank=True, null=True, verbose_name="latestPM02"),
                ),
                (
                    "taskOfPM02",
                    models.CharField(max_length=200, verbose_name="taskOfPM02"),
                ),
                (
                    "countOfPM03",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="countOfPM03"
                    ),
                ),
                (
                    "latestPM03",
                    models.DateField(blank=True, null=True, verbose_name="latestPM03"),
                ),
                (
                    "taskOfPM03",
                    models.CharField(max_length=200, verbose_name="taskOfPM03"),
                ),
                (
                    "countOfPM04",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="countOfPM04"
                    ),
                ),
                (
                    "latestPM04",
                    models.DateField(blank=True, null=True, verbose_name="latestPM04"),
                ),
                (
                    "taskOfPM04",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskOfPM04"
                    ),
                ),
                (
                    "countOfPM05",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="countOfPM05"
                    ),
                ),
                (
                    "latestPM05",
                    models.DateField(blank=True, null=True, verbose_name="latestPM05"),
                ),
                (
                    "taskOfPM05",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskOfPM05"
                    ),
                ),
                (
                    "nextEventDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="nextEventDate"
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="situation"
                    ),
                ),
                (
                    "ceDescription",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="ceDescription",
                    ),
                ),
                (
                    "thisYear10ago",
                    models.BooleanField(default=False, verbose_name="thisYear10ago"),
                ),
                (
                    "thisYear9ago",
                    models.BooleanField(default=False, verbose_name="thisYear9ago"),
                ),
                (
                    "thisYear8ago",
                    models.BooleanField(default=False, verbose_name="thisYear8ago"),
                ),
                (
                    "thisYear7ago",
                    models.BooleanField(default=False, verbose_name="thisYear7ago"),
                ),
                (
                    "thisYear6ago",
                    models.BooleanField(default=False, verbose_name="thisYear6ago"),
                ),
                (
                    "thisYear5ago",
                    models.BooleanField(default=False, verbose_name="thisYear5ago"),
                ),
                (
                    "thisYear4ago",
                    models.BooleanField(default=False, verbose_name="thisYear4ago"),
                ),
                (
                    "thisYear3ago",
                    models.BooleanField(default=False, verbose_name="thisYear3ago"),
                ),
                (
                    "thisYear2ago",
                    models.BooleanField(default=False, verbose_name="thisYear2ago"),
                ),
                (
                    "thisYear1ago",
                    models.BooleanField(default=False, verbose_name="thisYear1ago"),
                ),
                ("thisYear", models.CharField(max_length=200, verbose_name="thisYear")),
                (
                    "thisYear1later",
                    models.BooleanField(default=False, verbose_name="thisYear1later"),
                ),
                (
                    "thisYear2later",
                    models.BooleanField(default=False, verbose_name="thisYear2later"),
                ),
                (
                    "thisYear3later",
                    models.BooleanField(default=False, verbose_name="thisYear3later"),
                ),
                (
                    "thisYear4later",
                    models.BooleanField(default=False, verbose_name="thisYear4later"),
                ),
                (
                    "thisYear5later",
                    models.BooleanField(default=False, verbose_name="thisYear5later"),
                ),
                (
                    "thisYear6later",
                    models.BooleanField(default=False, verbose_name="thisYear6later"),
                ),
                (
                    "thisYear7later",
                    models.BooleanField(default=False, verbose_name="thisYear7later"),
                ),
                (
                    "thisYear8later",
                    models.BooleanField(default=False, verbose_name="thisYear8later"),
                ),
                (
                    "thisYear9later",
                    models.BooleanField(default=False, verbose_name="thisYear9later"),
                ),
                (
                    "thisYear10later",
                    models.BooleanField(default=False, verbose_name="thisYear10later"),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpareParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("image", models.ImageField(upload_to="", verbose_name="image")),
                (
                    "partsName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="partsName"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="category"
                    ),
                ),
                (
                    "partsModel",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="partsModel"
                    ),
                ),
                (
                    "serialNumber",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="serialNumber",
                    ),
                ),
                (
                    "taskListNo",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskListNo"
                    ),
                ),
                (
                    "partsCost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="partsCost",
                    ),
                ),
                (
                    "numberOf",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="numberOf"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="unit"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="location"
                    ),
                ),
                (
                    "partsDeliveryTime",
                    models.DurationField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="partsDeliveryTime",
                    ),
                ),
                (
                    "partsDescription",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="partsDescription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("plant", models.ImageField(upload_to="", verbose_name="plant")),
                (
                    "equipment",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="equipment"
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="function"
                    ),
                ),
                (
                    "latestPM02",
                    models.DateField(blank=True, null=True, verbose_name="latestPM02"),
                ),
                (
                    "latestPM03",
                    models.DateField(blank=True, null=True, verbose_name="latestPM03"),
                ),
                (
                    "latestPM04",
                    models.DateField(blank=True, null=True, verbose_name="latestPM04"),
                ),
                (
                    "taskOfPM02",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskOfPM02"
                    ),
                ),
                (
                    "laborCost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="laborCost",
                    ),
                ),
                (
                    "partsName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="partsName"
                    ),
                ),
                (
                    "constructionPeriod",
                    models.DurationField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="constructionPeriod",
                    ),
                ),
                (
                    "nextEventDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="nextEventDate"
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="situation"
                    ),
                ),
                (
                    "thisYear10ago",
                    models.BooleanField(default=False, verbose_name="thisYear10ago"),
                ),
                (
                    "thisYear9ago",
                    models.BooleanField(default=False, verbose_name="thisYear9ago"),
                ),
                (
                    "thisYear8ago",
                    models.BooleanField(default=False, verbose_name="thisYear8ago"),
                ),
                (
                    "thisYear7ago",
                    models.BooleanField(default=False, verbose_name="thisYear7ago"),
                ),
                (
                    "thisYear6ago",
                    models.BooleanField(default=False, verbose_name="thisYear6ago"),
                ),
                (
                    "thisYear5ago",
                    models.BooleanField(default=False, verbose_name="thisYear5ago"),
                ),
                (
                    "thisYear4ago",
                    models.BooleanField(default=False, verbose_name="thisYear4ago"),
                ),
                (
                    "thisYear3ago",
                    models.BooleanField(default=False, verbose_name="thisYear3ago"),
                ),
                (
                    "thisYear2ago",
                    models.BooleanField(default=False, verbose_name="thisYear2ago"),
                ),
                (
                    "thisYear1ago",
                    models.BooleanField(default=False, verbose_name="thisYear1ago"),
                ),
                ("thisYear", models.CharField(max_length=200, verbose_name="thisYear")),
                (
                    "thisYear1later",
                    models.BooleanField(default=False, verbose_name="thisYear1later"),
                ),
                (
                    "thisYear2later",
                    models.BooleanField(default=False, verbose_name="thisYear2later"),
                ),
                (
                    "thisYear3later",
                    models.BooleanField(default=False, verbose_name="thisYear3later"),
                ),
                (
                    "thisYear4later",
                    models.BooleanField(default=False, verbose_name="thisYear4later"),
                ),
                (
                    "thisYear5later",
                    models.BooleanField(default=False, verbose_name="thisYear5later"),
                ),
                (
                    "thisYear6later",
                    models.BooleanField(default=False, verbose_name="thisYear6later"),
                ),
                (
                    "thisYear7later",
                    models.BooleanField(default=False, verbose_name="thisYear7later"),
                ),
                (
                    "thisYear8later",
                    models.BooleanField(default=False, verbose_name="thisYear8later"),
                ),
                (
                    "thisYear9later",
                    models.BooleanField(default=False, verbose_name="thisYear9later"),
                ),
                (
                    "thisYear10later",
                    models.BooleanField(default=False, verbose_name="thisYear10later"),
                ),
            ],
        ),
    ]
