# Generated by Django 5.0.1 on 2024-03-06 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0001_initial"),
        ("spareParts", "0001_initial"),
        ("taskList", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SpareParts",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="category",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="constructionPeriod",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="countOfPM02",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="countOfPM03",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="countOfPM04",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="countOfPM05",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="laborOfPM02",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="latestPM02",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="latestPM03",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="latestPM04",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="latestPM05",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="nextEventDate",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="partsDeliveryTime",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="periodOfPM02",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="situation",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="taskOfPM02",
        ),
        migrations.AddField(
            model_name="ce",
            name="bomNo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="spareParts.spareparts",
            ),
        ),
        migrations.AddField(
            model_name="ce",
            name="taskListNo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="taskList.task",
            ),
        ),
    ]
