# Generated by Django 5.0.1 on 2024-03-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ce",
            name="thisYear",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear10ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear10later",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear1ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear1later",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear2ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear2later",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear3ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear3later",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear4ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear4later",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear5ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear5later",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear6ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear6later",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear7ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear7later",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear8ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear8later",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear9ago",
        ),
        migrations.RemoveField(
            model_name="ce",
            name="thisYear9later",
        ),
    ]
