# Generated by Django 5.0.1 on 2024-03-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="celist",
            name="taskListCode",
        ),
        migrations.AddField(
            model_name="celist",
            name="taskName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskName"
            ),
        ),
    ]
