# Generated by Django 5.0.1 on 2024-02-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePartsList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("image", models.ImageField(upload_to="", verbose_name="image")),
                (
                    "partsName",
                    models.CharField(max_length=200, verbose_name="partsName"),
                ),
                ("category", models.CharField(max_length=200, verbose_name="category")),
                (
                    "partsModel",
                    models.IntegerField(default=0, verbose_name="partsModel"),
                ),
                (
                    "serialNumber",
                    models.CharField(max_length=200, verbose_name="serialNumber"),
                ),
                (
                    "taskListNo",
                    models.CharField(max_length=200, verbose_name="taskListNo"),
                ),
                ("partsCost", models.IntegerField(default=0, verbose_name="partsCost")),
                ("numberOf", models.CharField(max_length=200, verbose_name="numberOf")),
                ("unit", models.CharField(max_length=200, verbose_name="unit")),
                ("location", models.IntegerField(default=0, verbose_name="location")),
                (
                    "partsDeliveryTime",
                    models.CharField(max_length=200, verbose_name="partsDeliveryTime"),
                ),
                (
                    "partsDescription",
                    models.CharField(max_length=200, verbose_name="partsDescription"),
                ),
            ],
        ),
    ]
