# Generated by Django 5.0.1 on 2024-03-10 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_companyname_options_alter_customuser_options"),
        ("ceList", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celist",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ceList_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="function",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plant_companyCode",
                to="accounts.companycode",
            ),
        ),
    ]
