# Generated by Django 5.0.1 on 2024-03-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0002_delete_spareparts_delete_task_remove_ce_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ce",
            name="bomNo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="bomNo"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="taskListNo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskListNo"
            ),
        ),
    ]
