# Generated by Django 5.0.1 on 2024-02-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0002_sparepartslist"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("plant", models.ImageField(upload_to="", verbose_name="plant")),
                (
                    "equipment",
                    models.CharField(max_length=200, verbose_name="equipment"),
                ),
                ("function", models.CharField(max_length=200, verbose_name="function")),
                (
                    "latestPM02",
                    models.IntegerField(default=0, verbose_name="latestPM02"),
                ),
                (
                    "latestPM03",
                    models.CharField(max_length=200, verbose_name="latestPM03"),
                ),
                (
                    "latestPM04",
                    models.CharField(max_length=200, verbose_name="latestPM04"),
                ),
                (
                    "taskOfPM02",
                    models.IntegerField(default=0, verbose_name="taskOfPM02"),
                ),
                (
                    "laborCost",
                    models.CharField(max_length=200, verbose_name="laborCost"),
                ),
                (
                    "partsName",
                    models.CharField(max_length=200, verbose_name="partsName"),
                ),
                (
                    "constructionPeriod",
                    models.IntegerField(default=0, verbose_name="constructionPeriod"),
                ),
                (
                    "nextEventDate",
                    models.CharField(max_length=200, verbose_name="nextEventDate"),
                ),
                (
                    "situation",
                    models.CharField(max_length=200, verbose_name="situation"),
                ),
                (
                    "thisYear10ago",
                    models.CharField(max_length=200, verbose_name="thisYear10ago"),
                ),
                (
                    "thisYear9ago",
                    models.CharField(max_length=200, verbose_name="thisYear9ago"),
                ),
                (
                    "thisYear8ago",
                    models.CharField(max_length=200, verbose_name="thisYear8ago"),
                ),
                (
                    "thisYear7ago",
                    models.CharField(max_length=200, verbose_name="thisYear7ago"),
                ),
                (
                    "thisYear6ago",
                    models.CharField(max_length=200, verbose_name="thisYear6ago"),
                ),
                (
                    "thisYear5ago",
                    models.CharField(max_length=200, verbose_name="thisYear5ago"),
                ),
                (
                    "thisYear4ago",
                    models.CharField(max_length=200, verbose_name="thisYear4ago"),
                ),
                (
                    "thisYear3ago",
                    models.CharField(max_length=200, verbose_name="thisYear3ago"),
                ),
                (
                    "thisYear2ago",
                    models.CharField(max_length=200, verbose_name="thisYear2ago"),
                ),
                (
                    "thisYear1ago",
                    models.CharField(max_length=200, verbose_name="thisYear1ago"),
                ),
                ("thisYear", models.CharField(max_length=200, verbose_name="thisYear")),
                (
                    "thisYear1later",
                    models.CharField(max_length=200, verbose_name="thisYear1later"),
                ),
                (
                    "thisYear2later",
                    models.CharField(max_length=200, verbose_name="thisYear2later"),
                ),
                (
                    "thisYear3later",
                    models.CharField(max_length=200, verbose_name="thisYear3later"),
                ),
                (
                    "thisYear4later",
                    models.CharField(max_length=200, verbose_name="thisYear4later"),
                ),
                (
                    "thisYear5later",
                    models.CharField(max_length=200, verbose_name="thisYear5later"),
                ),
                (
                    "thisYear6later",
                    models.CharField(max_length=200, verbose_name="thisYear6later"),
                ),
                (
                    "thisYear7later",
                    models.CharField(max_length=200, verbose_name="thisYear7later"),
                ),
                (
                    "thisYear8later",
                    models.CharField(max_length=200, verbose_name="thisYear8later"),
                ),
                (
                    "thisYear9later",
                    models.CharField(max_length=200, verbose_name="thisYear9later"),
                ),
                (
                    "thisYear10later",
                    models.CharField(max_length=200, verbose_name="thisYear10later"),
                ),
            ],
        ),
    ]
