# Generated by Django 5.0.1 on 2024-01-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celist", "0002_celist_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celist",
            name="cost_of_task",
            field=models.DecimalField(
                decimal_places=4, max_digits=10, verbose_name="推定コスト"
            ),
        ),
    ]
