# Generated by Django 5.0.1 on 2024-03-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0002_remove_celist_tasklistcode_celist_taskname"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeOfPM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "typeOfPM",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="typeOfPM"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="PMDescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "TypeOfPM",
                "verbose_name_plural": "TypeOfPM",
                "ordering": ("typeOfPM",),
            },
        ),
        migrations.AddField(
            model_name="celist",
            name="ceList_Id",
            field=models.CharField(
                blank=True,
                default=0,
                max_length=200,
                null=True,
                verbose_name="ceListNo",
            ),
        ),
        migrations.AlterField(
            model_name="celist",
            name="bomCode",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="bomCode"
            ),
        ),
        migrations.AlterField(
            model_name="celist",
            name="machineName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ceList_machineName",
                to="ceList.machine",
            ),
        ),
        migrations.AlterField(
            model_name="celist",
            name="taskName",
            field=models.CharField(
                blank=True,
                default=0,
                max_length=200,
                null=True,
                verbose_name="taskName",
            ),
        ),
        migrations.AddField(
            model_name="celist",
            name="typeOfPM",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ceList_typeOfPM",
                to="ceList.typeofpm",
            ),
        ),
    ]
