# Generated by Django 5.0.1 on 2024-03-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0003_remove_function_companycode_and_more"),
        ("spareParts", "0002_remove_spareparts_function_spareparts_machinename"),
        ("taskList", "0002_remove_tasklist_function_tasklist_machinename"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Function",
        ),
    ]
