# Generated by Django 5.0.1 on 2024-01-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celist", "0003_alter_celist_cost_of_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celist",
            name="cost_of_task",
            field=models.CharField(max_length=200, verbose_name="推定コスト"),
        ),
    ]
