# Generated by Django 5.0.1 on 2024-03-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0003_typeofpm_celist_celist_id_alter_celist_bomcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typeofpm",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="PMDescription"
            ),
        ),
    ]
