# Generated by Django 5.0.1 on 2024-02-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0003_tasklist"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CeList",
            new_name="Ce",
        ),
        migrations.RenameModel(
            old_name="SparePartsList",
            new_name="SpareParts",
        ),
        migrations.RenameModel(
            old_name="TaskList",
            new_name="Task",
        ),
    ]
