# Generated by Django 5.0.1 on 2024-03-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0004_rename_ce_celist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="celist",
            options={
                "ordering": ("ceListNo",),
                "verbose_name": "Critical equipment list",
                "verbose_name_plural": "Critical equipment list",
            },
        ),
    ]
