# Generated by Django 5.0.1 on 2024-02-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0004_rename_celist_ce_rename_sparepartslist_spareparts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ce",
            name="bomNo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="bomNo"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="ceDescription",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="ceDescription"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="ceListNo",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="ceListNo"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="companyCode",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="companyCode"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="constructionPeriod",
            field=models.DurationField(
                blank=True, default=0, null=True, verbose_name="constructionPeriod"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="countOfPM02",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM02"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="countOfPM03",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM03"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="countOfPM04",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM04"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="countOfPM05",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM05"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="equipment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="equipment"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="function",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="function"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="latestPM02",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM02"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="latestPM03",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM03"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="latestPM04",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM04"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="latestPM05",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM05"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="locationNo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="locationNo"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="mttr",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="mttr"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="nextEventDate",
            field=models.DateField(blank=True, null=True, verbose_name="nextEventDate"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="partsDeliveryTime",
            field=models.DurationField(
                blank=True, default=0, null=True, verbose_name="partsDeliveryTime"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="plant",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="plant"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="situation",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="situation"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="taskOfPM04",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskOfPM04"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="taskOfPM05",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskOfPM05"
            ),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear10ago",
            field=models.BooleanField(default=False, verbose_name="thisYear10ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear10later",
            field=models.BooleanField(default=False, verbose_name="thisYear10later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear1ago",
            field=models.BooleanField(default=False, verbose_name="thisYear1ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear1later",
            field=models.BooleanField(default=False, verbose_name="thisYear1later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear2ago",
            field=models.BooleanField(default=False, verbose_name="thisYear2ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear2later",
            field=models.BooleanField(default=False, verbose_name="thisYear2later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear3ago",
            field=models.BooleanField(default=False, verbose_name="thisYear3ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear3later",
            field=models.BooleanField(default=False, verbose_name="thisYear3later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear4ago",
            field=models.BooleanField(default=False, verbose_name="thisYear4ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear4later",
            field=models.BooleanField(default=False, verbose_name="thisYear4later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear5ago",
            field=models.BooleanField(default=False, verbose_name="thisYear5ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear5later",
            field=models.BooleanField(default=False, verbose_name="thisYear5later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear6ago",
            field=models.BooleanField(default=False, verbose_name="thisYear6ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear6later",
            field=models.BooleanField(default=False, verbose_name="thisYear6later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear7ago",
            field=models.BooleanField(default=False, verbose_name="thisYear7ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear7later",
            field=models.BooleanField(default=False, verbose_name="thisYear7later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear8ago",
            field=models.BooleanField(default=False, verbose_name="thisYear8ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear8later",
            field=models.BooleanField(default=False, verbose_name="thisYear8later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear9ago",
            field=models.BooleanField(default=False, verbose_name="thisYear9ago"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="thisYear9later",
            field=models.BooleanField(default=False, verbose_name="thisYear9later"),
        ),
        migrations.AlterField(
            model_name="ce",
            name="totalBomCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=5,
                null=True,
                verbose_name="totalBomCost",
            ),
        ),
    ]
