# Generated by Django 5.0.1 on 2024-03-16 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0004_alter_typeofpm_description"),
        ("taskList", "0006_remove_tasklist_equipment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalRepairingCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "repairingCost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repairing_cost_sum",
                        to="taskList.tasklist",
                    ),
                ),
            ],
        ),
    ]
