# Generated by Django 5.0.1 on 2024-02-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0005_alter_ce_bomno_alter_ce_cedescription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spareparts",
            name="category",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="category"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="location",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="location"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="numberOf",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="numberOf"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=5,
                null=True,
                verbose_name="partsCost",
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsDeliveryTime",
            field=models.DurationField(
                blank=True, default=0, null=True, verbose_name="partsDeliveryTime"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsDescription",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="partsDescription"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsModel",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="partsModel"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="partsName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="partsName"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="serialNumber",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="serialNumber"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="taskListNo",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskListNo"
            ),
        ),
        migrations.AlterField(
            model_name="spareparts",
            name="unit",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="unit"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="constructionPeriod",
            field=models.DurationField(
                blank=True, default=0, null=True, verbose_name="constructionPeriod"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="equipment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="equipment"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="function",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="function"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="laborCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=5,
                null=True,
                verbose_name="laborCost",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="latestPM02",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM02"),
        ),
        migrations.AlterField(
            model_name="task",
            name="latestPM03",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM03"),
        ),
        migrations.AlterField(
            model_name="task",
            name="latestPM04",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM04"),
        ),
        migrations.AlterField(
            model_name="task",
            name="nextEventDate",
            field=models.DateField(blank=True, null=True, verbose_name="nextEventDate"),
        ),
        migrations.AlterField(
            model_name="task",
            name="partsName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="partsName"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="situation",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="situation"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="taskOfPM02",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="taskOfPM02"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear10ago",
            field=models.BooleanField(default=False, verbose_name="thisYear10ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear10later",
            field=models.BooleanField(default=False, verbose_name="thisYear10later"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear1ago",
            field=models.BooleanField(default=False, verbose_name="thisYear1ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear1later",
            field=models.BooleanField(default=False, verbose_name="thisYear1later"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear2ago",
            field=models.BooleanField(default=False, verbose_name="thisYear2ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear2later",
            field=models.BooleanField(default=False, verbose_name="thisYear2later"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear3ago",
            field=models.BooleanField(default=False, verbose_name="thisYear3ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear3later",
            field=models.BooleanField(default=False, verbose_name="thisYear3later"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear4ago",
            field=models.BooleanField(default=False, verbose_name="thisYear4ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear4later",
            field=models.BooleanField(default=False, verbose_name="thisYear4later"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear5ago",
            field=models.BooleanField(default=False, verbose_name="thisYear5ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear5later",
            field=models.BooleanField(default=False, verbose_name="thisYear5later"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear6ago",
            field=models.BooleanField(default=False, verbose_name="thisYear6ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear6later",
            field=models.BooleanField(default=False, verbose_name="thisYear6later"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear7ago",
            field=models.BooleanField(default=False, verbose_name="thisYear7ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear7later",
            field=models.BooleanField(default=False, verbose_name="thisYear7later"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear8ago",
            field=models.BooleanField(default=False, verbose_name="thisYear8ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear8later",
            field=models.BooleanField(default=False, verbose_name="thisYear8later"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear9ago",
            field=models.BooleanField(default=False, verbose_name="thisYear9ago"),
        ),
        migrations.AlterField(
            model_name="task",
            name="thisYear9later",
            field=models.BooleanField(default=False, verbose_name="thisYear9later"),
        ),
    ]
