# Generated by Django 5.0.1 on 2024-03-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("ceList", "0005_totalrepairingcost"),
        (
            "repairingCost",
            "0003_alter_actualpm02_plant_alter_actualpm03_plant_and_more",
        ),
        ("sustainability", "0002_alter_co2_co2cost_alter_co2_plant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celist",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ceList_plant",
                to="accounts.plant",
            ),
        ),
        migrations.DeleteModel(
            name="Plant",
        ),
    ]
