# Generated by Django 5.0.1 on 2024-03-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0005_alter_celist_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celist",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
