# Generated by Django 5.0.1 on 2024-03-20 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("ceList", "0006_alter_celist_plant_delete_plant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="celist",
            name="machineName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="machineName"
            ),
        ),
        migrations.RemoveField(
            model_name="totalrepairingcost",
            name="task",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="typeOfPM",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="assessment",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="bomCode",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="ceDescription",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="coveredFromTask",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="impactForProduction",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="levelSetValue",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="mttr",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="possibilityOfProductionLv",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="probabilityOfFailure",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="rcaOrReplace",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="sparePartsOrAlternative",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="taskName",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="twoways",
        ),
        migrations.AddField(
            model_name="equipment",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_plant",
                to="accounts.plant",
            ),
        ),
        migrations.DeleteModel(
            name="Machine",
        ),
        migrations.DeleteModel(
            name="TotalRepairingCost",
        ),
        migrations.DeleteModel(
            name="TypeOfPM",
        ),
    ]
