# Generated by Django 5.0.1 on 2024-03-09 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customuser_payment"),
        ("ceList", "0006_alter_celist_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="celist",
            options={
                "ordering": ("ceListId",),
                "verbose_name": "Critical equipment list",
                "verbose_name_plural": "Critical equipment list",
            },
        ),
        migrations.RemoveField(
            model_name="celist",
            name="ceListNo",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="slug",
        ),
        migrations.AddField(
            model_name="celist",
            name="ceListId",
            field=models.CharField(
                blank=True,
                default=0,
                max_length=200,
                null=True,
                verbose_name="ceListNo",
            ),
        ),
        migrations.AlterField(
            model_name="celist",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="companyCode_company",
                to="accounts.company",
            ),
        ),
    ]
