# Generated by Django 5.0.1 on 2024-03-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0006_alter_celist_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="celist",
            options={
                "ordering": ("ceListId",),
                "verbose_name": "Critical equipment list",
                "verbose_name_plural": "Critical equipment list",
            },
        ),
        migrations.RemoveField(
            model_name="celist",
            name="ceListNo",
        ),
        migrations.RemoveField(
            model_name="celist",
            name="slug",
        ),
        migrations.AddField(
            model_name="celist",
            name="ceListId",
            field=models.CharField(
                blank=True,
                default=0,
                max_length=200,
                null=True,
                verbose_name="ceListNo",
            ),
        ),
    ]
