# Generated by Django 5.0.1 on 2024-03-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("ceList", "0007_alter_celist_machinename_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machineName",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="machineName",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machine_companyName",
                        to="accounts.companyname",
                    ),
                ),
            ],
            options={
                "verbose_name": "Machine",
                "verbose_name_plural": "Machine",
                "ordering": ("companyCode",),
            },
        ),
        migrations.AlterField(
            model_name="celist",
            name="machineName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ceList_machine",
                to="ceList.machine",
            ),
        ),
    ]
