# Generated by Django 5.0.1 on 2024-03-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0007_alter_celist_options_remove_celist_celistno_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="celist",
            old_name="bomNo",
            new_name="bomCode",
        ),
        migrations.RenameField(
            model_name="celist",
            old_name="taskListNo",
            new_name="taskListCode",
        ),
    ]
