# Generated by Django 5.0.1 on 2024-03-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0008_machine_alter_celist_machinename"),
    ]

    operations = [
        migrations.RenameField(
            model_name="celist",
            old_name="ceList_Id",
            new_name="ceListNo",
        ),
    ]
