# Generated by Django 5.0.1 on 2024-03-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0008_rename_bomno_celist_bomcode_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="celist",
            options={
                "ordering": ("plant",),
                "verbose_name": "Critical equipment list",
                "verbose_name_plural": "Critical equipment list",
            },
        ),
        migrations.RemoveField(
            model_name="celist",
            name="ceListId",
        ),
    ]
