# Generated by Django 5.0.1 on 2024-06-23 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("ceList", "0009_rename_celist_id_celist_celistno"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskMatrixPossibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="x"
                    ),
                ),
                (
                    "y",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="y"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riskMatrixPossibility_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="riskMatrixPossibility_companyName",
                        to="accounts.companyname",
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Matrix Possibility",
                "verbose_name_plural": "Risk Matrix Possibility",
                "ordering": ("-timestamp",),
            },
        ),
    ]
