# Generated by Django 5.0.1 on 2024-03-09 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_customuser_payment"),
        ("ceList", "0009_alter_celist_options_remove_celist_celistid"),
    ]

    operations = [
        migrations.AddField(
            model_name="celist",
            name="companyName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ceList_companyName",
                to="accounts.company",
            ),
        ),
        migrations.AlterField(
            model_name="celist",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ceList_companyCode",
                to="accounts.company",
            ),
        ),
    ]
