# Generated by Django 5.0.1 on 2024-08-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0011_riskmatriximpact"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskmatriximpact",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
