# Generated by Django 5.0.1 on 2024-08-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
        ("ceList", "0012_riskmatriximpact_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskmatrixpossibility",
            name="favoriteIndex",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Favorite Index"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="riskmatrixpossibility",
            unique_together={("companyCode", "favoriteIndex")},
        ),
    ]
