# Generated by Django 5.0.1 on 2024-08-31 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0013_riskmatrixpossibility_favoriteindex_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="riskmatrixpossibility",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="riskmatriximpact",
            name="favorite",
        ),
        migrations.RemoveField(
            model_name="riskmatrixpossibility",
            name="favoriteIndex",
        ),
    ]
