# Generated by Django 5.0.1 on 2024-07-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reliability", "0002_weibulldata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BayesianPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField()),
                ("failure_count", models.IntegerField()),
                ("failure_type", models.CharField(max_length=100)),
                ("failure_cause", models.CharField(max_length=100)),
                ("maintenance_type", models.CharField(max_length=100)),
                ("maintenance_result", models.CharField(max_length=100)),
            ],
        ),
    ]
