# Generated by Django 5.0.1 on 2024-07-13 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
        ("ceList", "0011_riskmatriximpact"),
        ("reliability", "0003_bayesianprediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="TroubleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="date",
                    ),
                ),
                (
                    "pmType",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="nearMissNo"
                    ),
                ),
                (
                    "failureContent",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="failureContent",
                    ),
                ),
                (
                    "failureType",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="nearMissNo"
                    ),
                ),
                (
                    "repairMethod",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="repairMethod",
                    ),
                ),
                (
                    "rootCause",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="rootCause"
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TroubleHistory_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TroubleHistory_equipment",
                        to="ceList.equipment",
                    ),
                ),
                (
                    "machineName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="TroubleHistory_machine",
                        to="ceList.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
