# Generated by Django 5.0.1 on 2024-07-13 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0011_riskmatriximpact"),
        ("reliability", "0005_troublehistory_repaircost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="troublehistory",
            name="ceListNo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="troubleHistory_ceListNo",
                to="ceList.celist",
            ),
        ),
        migrations.AlterField(
            model_name="troublehistory",
            name="failureType",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="failureType"
            ),
        ),
    ]
