# Generated by Django 5.0.1 on 2024-07-14 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
        ("ceList", "0011_riskmatriximpact"),
        ("reliability", "0006_troublehistory_celistno_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FailurePredictionPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="date",
                    ),
                ),
                (
                    "pmType",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="pmType"
                    ),
                ),
                (
                    "ceListNo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failurePredictionPoint_ceListNo",
                        to="ceList.celist",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failurePredictionPoint_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failurePredictionPoint_equipment",
                        to="ceList.equipment",
                    ),
                ),
                (
                    "machineName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failurePredictionPoint_machine",
                        to="ceList.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
