# Generated by Django 5.0.1 on 2024-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reliability", "0007_failurepredictionpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="failurepredictionpoint",
            name="ceListNo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ceListNo"
            ),
        ),
    ]
