# Generated by Django 5.0.1 on 2024-08-08 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
        ("ceList", "0011_riskmatriximpact"),
        ("reliability", "0008_alter_failurepredictionpoint_celistno"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reliability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mttr",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="mttr"
                    ),
                ),
                (
                    "mtbf",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="mtbf"
                    ),
                ),
                (
                    "mttf",
                    models.IntegerField(
                        blank=True, max_length=50, null=True, verbose_name="mttf"
                    ),
                ),
                (
                    "totalOperatingTime",
                    models.FloatField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="totalOperatingTime",
                    ),
                ),
                (
                    "failureCount",
                    models.IntegerField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="failureCount",
                    ),
                ),
                (
                    "ceListNo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reliability_ceListNo",
                        to="ceList.celist",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reliability_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reliability_equipment",
                        to="ceList.equipment",
                    ),
                ),
                (
                    "machineName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reliability_machine",
                        to="ceList.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-mttr"],
            },
        ),
        migrations.DeleteModel(
            name="BayesianPrediction",
        ),
        migrations.DeleteModel(
            name="FailureData",
        ),
        migrations.DeleteModel(
            name="WeibullData",
        ),
    ]
