# Generated by Django 5.0.1 on 2024-08-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reliability", "0009_reliability_delete_bayesianprediction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reliability",
            name="failureCount",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="failureCount"
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="mtbf",
            field=models.IntegerField(blank=True, null=True, verbose_name="mtbf"),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="mttf",
            field=models.IntegerField(blank=True, null=True, verbose_name="mttf"),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="mttr",
            field=models.IntegerField(blank=True, null=True, verbose_name="mttr"),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="totalOperatingTime",
            field=models.FloatField(
                blank=True, null=True, verbose_name="totalOperatingTime"
            ),
        ),
    ]
