# Generated by Django 5.0.1 on 2024-08-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reliability", "0011_reliability_componentcondition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reliability",
            name="componentCondition",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Component Condition"
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="environmentCondition",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Environmental Conditions"
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="failureCause",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "過負荷"), (2, "摩耗"), (3, "環境要因")],
                null=True,
                verbose_name="Failure Cause",
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="failureMode",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "PM03"), (2, "PM04")],
                null=True,
                verbose_name="Failure Mode",
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="failureType",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "機械的故障"), (2, "電気的故障"), (3, "両方")],
                null=True,
                verbose_name="Failure Type",
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="maintenanceMethod",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "検査"), (2, "定期保全"), (3, "部品交換"), (4, "オーバーホール")],
                null=True,
                verbose_name="Maintenance Method",
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="operationalCondition",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "通常運転"), (1, "過負荷"), (2, "過熱")],
                null=True,
                verbose_name="Operational Conditions",
            ),
        ),
    ]
