# Generated by Django 5.0.1 on 2024-10-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reliability", "0013_reliability_record_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reliability",
            name="componentCondition",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="environmentCondition",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="maintenanceFrequency",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="maintenanceImpact",
        ),
        migrations.AddField(
            model_name="reliability",
            name="PMType",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "PM01"),
                    (2, "PM02"),
                    (3, "PM03"),
                    (4, "PM04"),
                    (5, "PM05"),
                ],
                null=True,
                verbose_name="PM Type",
            ),
        ),
        migrations.AddField(
            model_name="reliability",
            name="failureCauseDetail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Failure Cause Detail"
            ),
        ),
        migrations.AddField(
            model_name="reliability",
            name="failureDate",
            field=models.DateField(blank=True, null=True, verbose_name="Failure Date"),
        ),
        migrations.AddField(
            model_name="reliability",
            name="failureModeDetail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Failure Mode Detail"
            ),
        ),
        migrations.AddField(
            model_name="reliability",
            name="failureTypeDetail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Failure Type Detail"
            ),
        ),
        migrations.AddField(
            model_name="reliability",
            name="maintenanceMethodDetail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Maintenance Method Detail"
            ),
        ),
        migrations.AddField(
            model_name="reliability",
            name="maintenanceTitle",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Maintenance Title"
            ),
        ),
        migrations.AddField(
            model_name="reliability",
            name="operationalConditionDetail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Operational Condition Detail"
            ),
        ),
        migrations.AddField(
            model_name="reliability",
            name="plant",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Plant"
            ),
        ),
        migrations.AddField(
            model_name="reliability",
            name="remark",
            field=models.TextField(blank=True, null=True, verbose_name="Remark"),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="failureCause",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Human Error (人的ミス)"),
                    (2, "Fatigue Failure (疲労破壊)"),
                    (3, "Overheating/Overload (過熱 / 過負荷)"),
                    (4, "Misuse (誤使用)"),
                    (5, "Operational Error (操作ミス)"),
                    (6, "Manufacturing Defect (製造欠陥)"),
                    (7, "Inadequate Maintenance (不適切な保守)"),
                    (8, "Improper Installation (不適切な設置)"),
                    (9, "Material Issue (材料の問題)"),
                    (10, "Progressive Damage (進行的な損傷)"),
                    (11, "Corrosion (腐食)"),
                    (12, "Control System Failure (制御系の異常)"),
                    (13, "Process Defect (工程の欠陥)"),
                    (14, "External Factor (外部要因)"),
                    (15, "Natural Disaster (天変地異)"),
                    (16, "Other (その他)"),
                ],
                null=True,
                verbose_name="Failure Cause",
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="failureMode",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Wear (摩耗)"),
                    (2, "Fatigue Failure (疲労破壊)"),
                    (3, "Corrosion (腐食)"),
                    (4, "Overheating (過熱)"),
                    (5, "Inadequate Lubrication (潤滑不足)"),
                    (6, "Seal Failure (シール破損)"),
                    (7, "Overload (過負荷)"),
                    (8, "Vibration (振動)"),
                    (9, "Electrical Insulation Failure (絶縁破壊)"),
                    (10, "Short Circuit (短絡)"),
                    (11, "Mechanical Shock (機械的衝撃)"),
                    (12, "Thermal Fatigue (熱疲労)"),
                    (13, "Cavitation (キャビテーション)"),
                    (14, "Frictional Wear (摩擦摩耗)"),
                    (15, "Stress Corrosion Cracking (応力腐食割れ)"),
                    (16, "Erosion (浸食)"),
                    (17, "Oxidation (酸化)"),
                    (18, "Cable Breakage (ケーブル断線)"),
                    (19, "Bearing Failure (ベアリング破損)"),
                    (20, "Electronic Component Failure (電子部品故障)"),
                    (21, "Piping Leak (配管漏れ)"),
                    (22, "Piping Blockage (配管閉塞)"),
                    (23, "Building Structural Failure (建物の構造的問題)"),
                    (24, "Utility Failure (ユーティリティ故障)"),
                    (25, "Other (その他)"),
                ],
                null=True,
                verbose_name="Failure Mode",
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="failureType",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Electrical"),
                    (2, "Mechanical"),
                    (3, "Software"),
                    (4, "Building"),
                    (5, "Utility"),
                ],
                null=True,
                verbose_name="Failure Type",
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="maintenanceMethod",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Inspection (点検 / Inspection)"),
                    (2, "Lubrication (潤滑 / Lubrication)"),
                    (3, "Adjustment (調整 / Adjustment)"),
                    (4, "Replacement (交換 / Replacement)"),
                    (5, "Cleaning (清掃 / Cleaning)"),
                    (6, "Repair (修理 / Repair)"),
                    (7, "Regular Maintenance (定期保全 / Regular Maintenance)"),
                    (8, "Overhaul (オーバーホール / Overhaul)"),
                    (9, "Improvement (改善)"),
                    (10, "New Installation (新規設置)"),
                    (11, "Other (その他 / Other)"),
                ],
                null=True,
                verbose_name="Maintenance Method",
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="operationalCondition",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "Normal Operation (正常運転)"),
                    (1, "Abnormal Operation (異常運転)"),
                    (2, "Stopped (停止)"),
                    (3, "Maintenance Ongoing (保全中)"),
                    (4, "Under Investigation (調査中)"),
                ],
                null=True,
                verbose_name="Operational Conditions",
            ),
        ),
    ]
