# Generated by Django 5.0.1 on 2024-10-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reliability", "0014_remove_reliability_componentcondition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reliability",
            name="PMType",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "PM01: Inspection (検査)"),
                    (2, "PM02: Preventive Maintenance (予防保全)"),
                    (3, "PM03: Corrective Maintenance (修正保全)"),
                    (4, "PM04: Breakdown Maintenance (緊急保全)"),
                    (5, "PM05: Improvement (改善改造)"),
                    (6, "PM06"),
                    (7, "PM07"),
                    (8, "PM08"),
                    (9, "PM09"),
                    (10, "PM10"),
                ],
                null=True,
                verbose_name="PM Type",
            ),
        ),
        migrations.AlterField(
            model_name="reliability",
            name="maintenanceMethod",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Inspection (点検)"),
                    (2, "Lubrication (潤滑)"),
                    (3, "Adjustment (調整)"),
                    (4, "Replacement (交換)"),
                    (5, "Cleaning (清掃)"),
                    (6, "Repair (修理)"),
                    (7, "Regular Maintenance (定期保全)"),
                    (8, "Overhaul (オーバーホール)"),
                    (9, "Improvement (改善)"),
                    (10, "New Installation (新規設置)"),
                    (11, "Other (その他)"),
                ],
                null=True,
                verbose_name="Maintenance Method",
            ),
        ),
    ]
