# Generated by Django 5.0.1 on 2024-10-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reliability", "0015_alter_reliability_pmtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reliability",
            name="componentCondition",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Partial Replacement (一部交換)"),
                    (2, "Full Replacement (全部交換)"),
                    (3, "Continue Using Without Replacement (交換せずに継続使用)"),
                ],
                null=True,
                verbose_name="Component Condition",
            ),
        ),
        migrations.AddField(
            model_name="reliability",
            name="componentConditionDetail",
            field=models.TextField(
                blank=True, null=True, verbose_name="Component Condition Detail"
            ),
        ),
    ]
