# Generated by Django 5.0.1 on 2024-10-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reliability", "0016_reliability_componentcondition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reliability",
            name="maintenanceFrequency",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="maintenanceFrequency"
            ),
        ),
    ]
