# Generated by Django 5.0.1 on 2024-10-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reliability", "0017_reliability_maintenancefrequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reliability",
            name="componentConditionDetail",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="failureCauseDetail",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="failureModeDetail",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="failureTypeDetail",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="maintenanceMethodDetail",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="maintenanceTitle",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="operationalConditionDetail",
        ),
        migrations.RemoveField(
            model_name="reliability",
            name="remark",
        ),
    ]
