# Generated by Django 5.0.1 on 2024-04-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caltableactualpm02",
            name="no1HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm02",
            name="no1LowCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1LowCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm02",
            name="no2HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm02",
            name="no3HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm02",
            name="no4HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm02",
            name="no5HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm03",
            name="no1HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm03",
            name="no1LowCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1LowCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm03",
            name="no2HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm03",
            name="no3HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm03",
            name="no4HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm03",
            name="no5HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm04",
            name="no1HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm04",
            name="no1LowCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1LowCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm04",
            name="no2HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm04",
            name="no3HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm04",
            name="no4HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm04",
            name="no5HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm05",
            name="no1HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm05",
            name="no1LowCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1LowCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm05",
            name="no2HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm05",
            name="no3HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm05",
            name="no4HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableactualpm05",
            name="no5HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm02",
            name="no1HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm02",
            name="no1LowCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1LowCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm02",
            name="no2HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm02",
            name="no3HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm02",
            name="no4HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm02",
            name="no5HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm03",
            name="no1HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm03",
            name="no1LowCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1LowCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm03",
            name="no2HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm03",
            name="no3HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm03",
            name="no4HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm03",
            name="no5HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm05",
            name="no1HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm05",
            name="no1LowCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no1LowCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm05",
            name="no2HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no2HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm05",
            name="no3HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no3HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm05",
            name="no4HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no4HighCostTask"
            ),
        ),
        migrations.AddField(
            model_name="caltableplannedpm05",
            name="no5HighCostTask",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="no5HighCostTask"
            ),
        ),
    ]
