# Generated by Django 5.0.1 on 2024-04-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculation", "0002_caltableactualpm02_no1highcosttask_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caltableplannedpm02",
            options={"verbose_name_plural": "CalTablePlannedPM02"},
        ),
        migrations.AlterModelOptions(
            name="caltableplannedpm03",
            options={"verbose_name_plural": "CalTablePlannedPM03"},
        ),
        migrations.AlterModelOptions(
            name="caltableplannedpm05",
            options={"verbose_name_plural": "CalTablePlannedPM05"},
        ),
    ]
