# Generated by Django 5.0.1 on 2024-04-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation", "0005_summedplannedcost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summedplannedcost",
            name="totalActualCost",
        ),
        migrations.RemoveField(
            model_name="summedplannedcost",
            name="totalActualPM02",
        ),
        migrations.RemoveField(
            model_name="summedplannedcost",
            name="totalActualPM03",
        ),
        migrations.RemoveField(
            model_name="summedplannedcost",
            name="totalActualPM04",
        ),
        migrations.RemoveField(
            model_name="summedplannedcost",
            name="totalActualPM05",
        ),
        migrations.AddField(
            model_name="summedplannedcost",
            name="totalPlannedCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="totalPlannedCost",
            ),
        ),
        migrations.AddField(
            model_name="summedplannedcost",
            name="totalPlannedPM02",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="totalPlannedPM02",
            ),
        ),
        migrations.AddField(
            model_name="summedplannedcost",
            name="totalPlannedPM03",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="totalPlannedPM03",
            ),
        ),
        migrations.AddField(
            model_name="summedplannedcost",
            name="totalPlannedPM04",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="totalPlannedPM04",
            ),
        ),
        migrations.AddField(
            model_name="summedplannedcost",
            name="totalPlannedPM05",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="totalPlannedPM05",
            ),
        ),
    ]
