# Generated by Django 5.0.1 on 2024-04-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation", "0006_remove_summedplannedcost_totalactualcost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summedplannedcost",
            name="sumMar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="sumMay",
            ),
        ),
    ]
