from rest_framework import serializers
from .models import CeList,SparePartsList,TaskList


class CeListSerializer(serializers.ModelSerializer):
    class Meta:
        model = CeList # 呼び出すモデル
        fields = [
            "ceListNo",
            "companyCode",
            "plant",
            "locationNo",
            "function",
            "equipment",
            "bomNo",
            "totalBomCost",
            "valueImpact",
            "partsDeliveryTime",
            "mttr",
            "countOfPM02",
            "latestPM02",
            "taskOfPM02",
            "countOfPM03",
            "latestPM03",
            "taskOfPM03",
            "countOfPM04",
            "latestPM04",
            "taskOfPM04",
            "countOfPM05",
            "latestPM05",
            "taskOfPM05",
            'nextEventDate',
            'situation',
            'ceDescription',
            'thisYear10ago',
            'thisYear9ago',
            'thisYear8ago',
            'thisYear7ago',
            'thisYear6ago',
            'thisYear5ago',
            'thisYear4ago',
            'thisYear3ago',
            'thisYear2ago',
            'thisYear1ago',
            'thisYear',
            'thisYear1later',
            'thisYear2later',
            'thisYear3later',
            'thisYear4later',
            'thisYear5later',
            'thisYear6later',
            'thisYear7later',
            'thisYear8later',
            'thisYear9later',
            'thisYear10later',
        ] # API上に表示するモデルのデータ項目

class SparePartsListSerializer(serializers.ModelSerializer):
    class Meta:
        model = SparePartsList # 呼び出すモデル
        fields = [
            "image",
            "partsName",
            "category",
            "partsModel",
            "serialNumber",
            "taskListNo",
            "partsCost",
            "numberOf",
            "unit",
            "location",
            "partsDeliveryTime",
            "partsDescription",
        ] # API上に表示するモデルのデータ項目

class TaskListSerializer(serializers.ModelSerializer):
    class Meta:
        model = TaskList # 呼び出すモデル
        fields = [
            "plant",
            "equipment",
            "function",
            "latestPM02",
            "latestPM03",
            "latestPM04",
            "taskOfPM02",
            "laborCost",
            "partsName",
            "constructionPeriod",
            "nextEventDate",
            "situation",
            'thisYear10ago',
            'thisYear9ago',
            'thisYear8ago',
            'thisYear7ago',
            'thisYear6ago',
            'thisYear5ago',
            'thisYear4ago',
            'thisYear3ago',
            'thisYear2ago',
            'thisYear1ago',
            'thisYear',
            'thisYear1later',
            'thisYear2later',
            'thisYear3later',
            'thisYear4later',
            'thisYear5later',
            'thisYear6later',
            'thisYear7later',
            'thisYear8later',
            'thisYear9later',
            'thisYear10later',
        ] # API上に表示するモデルのデータ項目