# Generated by Django 5.0.1 on 2024-06-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ImageAnalysis",
        ),
    ]
