# Generated by Django 5.0.1 on 2024-06-18 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_rename_image_imageanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageanalysis",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imageanalysis",
            name="predicted_label",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
