# Generated by Django 4.1.3 on 2023-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plant", models.CharField(max_length=200, verbose_name="プラント名")),
                ("equipment", models.CharField(max_length=200, verbose_name="設備名称")),
                ("function", models.CharField(max_length=200, verbose_name="機能場所")),
                (
                    "setting_value_impact",
                    models.CharField(max_length=200, verbose_name="impactへの設定値"),
                ),
                (
                    "construction_period",
                    models.CharField(max_length=200, verbose_name="工期"),
                ),
                (
                    "parts_deliver_date",
                    models.CharField(max_length=200, verbose_name="部品納期"),
                ),
                ("mttr", models.CharField(max_length=200, verbose_name="MTTR")),
                (
                    "number_pm02",
                    models.CharField(max_length=200, verbose_name="PM02回数"),
                ),
                (
                    "latest_pm02",
                    models.CharField(max_length=200, verbose_name="直近のPM02"),
                ),
                (
                    "number_pm03",
                    models.CharField(max_length=200, verbose_name="PM03回数"),
                ),
                (
                    "latest_pm03",
                    models.CharField(max_length=200, verbose_name="直剣のPM03"),
                ),
                (
                    "number_pm04",
                    models.CharField(max_length=200, verbose_name="PM04回数"),
                ),
                (
                    "latest_pm04",
                    models.CharField(max_length=200, verbose_name="直近のPM04"),
                ),
                (
                    "impact_production",
                    models.CharField(max_length=200, verbose_name="生産へのimpact"),
                ),
                (
                    "possibility_of_failure",
                    models.CharField(max_length=200, verbose_name="故障の可能性"),
                ),
                ("assessment", models.CharField(max_length=200, verbose_name="評価")),
                (
                    "task_pm02",
                    models.CharField(max_length=200, verbose_name="PM02タスク名称"),
                ),
                (
                    "cost_of_task",
                    models.CharField(max_length=200, verbose_name="推定コスト"),
                ),
                ("period_of_task", models.CharField(max_length=200, verbose_name="周期")),
                ("next_event", models.CharField(max_length=200, verbose_name="次回の発生日")),
                (
                    "situation_for_pm02",
                    models.CharField(max_length=200, verbose_name="周期超過の有無"),
                ),
            ],
        ),
    ]
