# Generated by Django 4.1.3 on 2023-10-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=200, verbose_name="本の名前")),
                ("author", models.CharField(max_length=200, verbose_name="作者")),
                ("publisher", models.CharField(max_length=200, verbose_name="出版社")),
                ("price", models.CharField(max_length=200, verbose_name="価格")),
            ],
        ),
    ]
