# Generated by Django 5.0.1 on 2024-04-09 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_plant"),
        ("spareParts", "0014_bomlist_companycode"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eventDate",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="eventDate",
                    ),
                ),
                (
                    "deliveryTime",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="deliveryTime"
                    ),
                ),
                (
                    "orderAlertDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="orderAlertDate"
                    ),
                ),
                (
                    "safetyRate",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="safetyRate"
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertSchedule_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertSchedule_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertSchedule_areaCode",
                        to="accounts.areacode",
                    ),
                ),
                (
                    "partsName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertSchedule_partsName",
                        to="spareParts.bomlist",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertSchedule_plant",
                        to="accounts.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AlertSchedule",
                "verbose_name_plural": "AlertSchedule",
                "ordering": ("companyCode",),
            },
        ),
    ]
