# Generated by Django 5.0.1 on 2024-05-05 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agora", "0002_rename_location_alertschedule_country_and_more"),
        ("spareParts", "0017_remove_spareparts_inventoryturnover_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertschedule",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alertSchedule_location",
                to="spareParts.spareparts",
            ),
        ),
    ]
