# Generated by Django 5.0.1 on 2024-06-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("manufacturer", models.CharField(max_length=255)),
                ("model_number", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
    ]
