# Generated by Django 5.0.1 on 2024-06-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workingReport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentspecification",
            name="images",
            field=models.JSONField(default=list),
        ),
    ]
