# Generated by Django 5.0.1 on 2024-06-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workingReport", "0002_equipmentspecification_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipmentspecification",
            name="images",
        ),
        migrations.AddField(
            model_name="equipmentspecification",
            name="image1",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipment_images/"
            ),
        ),
        migrations.AddField(
            model_name="equipmentspecification",
            name="image1_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipmentspecification",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipment_images/"
            ),
        ),
        migrations.AddField(
            model_name="equipmentspecification",
            name="image2_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="equipmentspecification",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="equipment_images/"
            ),
        ),
        migrations.AddField(
            model_name="equipmentspecification",
            name="image3_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipmentspecification",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipmentspecification",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="equipmentspecification",
            name="model_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="equipmentspecification",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="equipmentspecification",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
