# Generated by Django 5.0.1 on 2024-06-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workingReport", "0003_remove_equipmentspecification_images_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="inspection_forms/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("extracted_text", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
