# Generated by Django 5.0.1 on 2024-09-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workingReport", "0004_inspectionform"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceWorkingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_code", models.CharField(max_length=255)),
                ("task_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("equipment", models.CharField(max_length=255)),
                ("part_name", models.CharField(blank=True, max_length=255, null=True)),
                ("reporter", models.CharField(max_length=255)),
                ("pm_type", models.CharField(max_length=255)),
                ("images", models.JSONField(default=list)),
                ("additional_notes", models.JSONField(default=list)),
                ("summary_remarks", models.TextField(blank=True, null=True)),
                ("pdf_file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="EquipmentSpecification",
        ),
    ]
