# Generated by Django 5.0.1 on 2024-09-01 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workingReport", "0005_maintenanceworkingreport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenanceworkingreport",
            name="additional_notes",
        ),
        migrations.RemoveField(
            model_name="maintenanceworkingreport",
            name="images",
        ),
    ]
