# Generated by Django 5.0.1 on 2024-09-01 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
        (
            "workingReport",
            "0006_remove_maintenanceworkingreport_additional_notes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Specsheets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("pdf_file", models.FileField(upload_to="pdfs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specsheets_companyCode",
                        to="accounts.companycode",
                    ),
                ),
            ],
        ),
    ]
