# Generated by Django 5.0.1 on 2024-10-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="project_files/")),
                (
                    "categories",
                    models.CharField(
                        choices=[
                            ("Mechanical", "Mechanical"),
                            ("Electrical", "Electrical"),
                            ("Software", "Software"),
                            ("Building", "Building"),
                            ("Utilities", "Utilities"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("uploaded_by", models.CharField(max_length=255)),
                ("registration_date", models.DateField()),
                ("tag", models.TextField(blank=True)),
            ],
        ),
    ]
