# Generated by Django 5.0.1 on 2024-10-05 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_plant_options_remove_plant_plantname_and_more"),
        ("projectManagement", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmanagement",
            old_name="project_name",
            new_name="projectName",
        ),
        migrations.RenameField(
            model_name="projectmanagement",
            old_name="registration_date",
            new_name="registrationDate",
        ),
        migrations.RenameField(
            model_name="projectmanagement",
            old_name="uploaded_by",
            new_name="uploadedBy",
        ),
        migrations.AddField(
            model_name="projectmanagement",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projectManagement_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="projectmanagement",
            name="categories",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="projectmanagement",
            name="file",
            field=models.FileField(upload_to="cad_files/"),
        ),
    ]
