# Generated by Django 5.0.1 on 2024-10-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projectManagement",
            "0002_rename_project_name_projectmanagement_projectname_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmanagement",
            name="categories",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectmanagement",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="cad_files/"),
        ),
        migrations.AlterField(
            model_name="projectmanagement",
            name="registrationDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectmanagement",
            name="tag",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectmanagement",
            name="uploadedBy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
