# Generated by Django 5.0.1 on 2024-03-05 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NearMiss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("nearMissListNo", models.IntegerField(blank=True, null=True)),
                (
                    "userName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="userName"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="department"
                    ),
                ),
                (
                    "dateOfOccurrence",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="dateOfOccurrence",
                    ),
                ),
                (
                    "placeOfOccurrence",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="placeOfOccurrence",
                    ),
                ),
                (
                    "typeOfAccident",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="typeOfAccident",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "factor",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="factor"
                    ),
                ),
                (
                    "injuredLv",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="injuredLv"
                    ),
                ),
                (
                    "equipmentDamageLv",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="equipmentDamageLv",
                    ),
                ),
                (
                    "affectOfEnviroment",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="affectOfEnviroment",
                    ),
                ),
                (
                    "newsCoverage",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="newsCoverage",
                    ),
                ),
                (
                    "safetyIndicater",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="safetyIndicater",
                    ),
                ),
                (
                    "measures",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="measures"
                    ),
                ),
                (
                    "totalOfNearMiss",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "createdDay",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="createdDay"
                    ),
                ),
                (
                    "updateDay",
                    models.DateTimeField(auto_now_add=True, verbose_name="updatedDay"),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.company",
                    ),
                ),
            ],
        ),
    ]
