# Generated by Django 5.0.1 on 2024-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NearMissList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                (
                    "nearMissListNo",
                    models.CharField(max_length=200, verbose_name="Near Miss List No"),
                ),
                ("userName", models.CharField(max_length=200, verbose_name="設備名称")),
                ("department", models.CharField(max_length=200, verbose_name="機能場所")),
                (
                    "dateOfOccurrence",
                    models.CharField(max_length=200, verbose_name="impactへの設定値"),
                ),
                (
                    "placeOfOccurrence",
                    models.CharField(max_length=200, verbose_name="工期"),
                ),
                (
                    "typeOfAccident",
                    models.CharField(max_length=200, verbose_name="部品納期"),
                ),
                ("description", models.CharField(max_length=200, verbose_name="MTTR")),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
