# Generated by Django 5.0.1 on 2024-03-12 17:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NearMiss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nearMissListNo", models.IntegerField(blank=True, null=True)),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="department"
                    ),
                ),
                (
                    "dateOfOccurrence",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="dateOfOccurrence",
                    ),
                ),
                (
                    "placeOfOccurrence",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="placeOfOccurrence",
                    ),
                ),
                (
                    "typeOfAccident",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="typeOfAccident",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "factor",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="factor"
                    ),
                ),
                (
                    "injuredLv",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="injuredLv"
                    ),
                ),
                (
                    "equipmentDamageLv",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="equipmentDamageLv",
                    ),
                ),
                (
                    "affectOfEnviroment",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="affectOfEnviroment",
                    ),
                ),
                (
                    "newsCoverage",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="newsCoverage",
                    ),
                ),
                (
                    "safetyIndicater",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="safetyIndicater",
                    ),
                ),
                (
                    "measures",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="measures"
                    ),
                ),
                (
                    "totalOfNearMiss",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "createdDay",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="createdDay",
                    ),
                ),
                (
                    "updateDay",
                    models.DateTimeField(auto_now_add=True, verbose_name="updatedDay"),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearMiss_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearMiss_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "userName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearMiss_userName",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Near Miss List",
                "verbose_name_plural": "Near Miss List",
                "ordering": ("-createdDay",),
            },
        ),
    ]
