# Generated by Django 5.0.1 on 2024-03-03 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_company_payment_userinfo_customuser_company_and_more"),
        ("nearMiss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nearmiss",
            name="company",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.company",
            ),
        ),
    ]
