# Generated by Django 5.0.1 on 2024-02-27 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nearmiss",
            name="createdDay",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="createdDay"
            ),
        ),
        migrations.AlterField(
            model_name="nearmiss",
            name="dateOfOccurrence",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="dateOfOccurrence"
            ),
        ),
        migrations.AlterField(
            model_name="nearmiss",
            name="updateDay",
            field=models.DateTimeField(auto_now_add=True, verbose_name="updatedDay"),
        ),
    ]
