# Generated by Django 5.0.1 on 2024-03-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nearmiss",
            old_name="nearMissListNo",
            new_name="nearMissNo",
        ),
    ]
