# Generated by Django 5.0.1 on 2024-03-10 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="nearmiss",
            name="createdDay",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="createdDay",
            ),
        ),
        migrations.AlterField(
            model_name="nearmiss",
            name="userName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearMiss_userName",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
