# Generated by Django 5.0.1 on 2024-02-23 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nearmisslist",
            name="affectOfEnviroment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="affectOfEnviroment"
            ),
        ),
        migrations.AddField(
            model_name="nearmisslist",
            name="createdDay",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                max_length=200,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="nearmisslist",
            name="equipmentDamageLv",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="equipmentDamageLv"
            ),
        ),
        migrations.AddField(
            model_name="nearmisslist",
            name="factor",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="factor"
            ),
        ),
        migrations.AddField(
            model_name="nearmisslist",
            name="injuredLv",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="injuredLv"
            ),
        ),
        migrations.AddField(
            model_name="nearmisslist",
            name="measures",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="measures"
            ),
        ),
        migrations.AddField(
            model_name="nearmisslist",
            name="newsCoverage",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="newsCoverage"
            ),
        ),
        migrations.AddField(
            model_name="nearmisslist",
            name="safetyIndicater",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="safetyIndicater"
            ),
        ),
        migrations.AlterField(
            model_name="nearmisslist",
            name="dateOfOccurrence",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                max_length=200,
                verbose_name="dateOfOccurrence",
            ),
        ),
        migrations.AlterField(
            model_name="nearmisslist",
            name="department",
            field=models.CharField(max_length=200, verbose_name="department"),
        ),
        migrations.AlterField(
            model_name="nearmisslist",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="nearmisslist",
            name="nearMissListNo",
            field=models.CharField(max_length=200, verbose_name="NearMissListNo"),
        ),
        migrations.AlterField(
            model_name="nearmisslist",
            name="placeOfOccurrence",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="placeOfOccurrence"
            ),
        ),
        migrations.AlterField(
            model_name="nearmisslist",
            name="typeOfAccident",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="typeOfAccident"
            ),
        ),
        migrations.AlterField(
            model_name="nearmisslist",
            name="userName",
            field=models.CharField(max_length=200, verbose_name="userName"),
        ),
    ]
