# Generated by Django 5.0.1 on 2024-03-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nearmiss",
            options={
                "ordering": ("-createdDay",),
                "verbose_name": "Near Miss List",
                "verbose_name_plural": "Near Miss List",
            },
        ),
    ]
