# Generated by Django 5.0.1 on 2024-03-10 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_companyname_options_alter_customuser_options"),
        ("nearMiss", "0002_alter_nearmiss_createdday_alter_nearmiss_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="nearmiss",
            name="companyName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.companyname",
            ),
        ),
        migrations.AlterField(
            model_name="nearmiss",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="nearmiss",
            name="dateOfOccurrence",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="dateOfOccurrence",
            ),
        ),
    ]
