# Generated by Django 5.0.1 on 2024-02-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0002_alter_nearmiss_createdday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nearmiss",
            name="description",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="description"
            ),
        ),
    ]
