# Generated by Django 5.0.1 on 2024-02-25 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0002_nearmisslist_affectofenviroment_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NearMissList",
            new_name="NearMiss",
        ),
    ]
