# Generated by Django 5.0.1 on 2024-03-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0002_alter_nearmiss_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nearmiss",
            name="slug",
        ),
    ]
