# Generated by Django 5.0.1 on 2024-03-03 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0002_nearmiss_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nearmiss",
            old_name="company",
            new_name="companyCode",
        ),
    ]
