# Generated by Django 5.0.1 on 2024-03-16 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("nearMiss", "0002_rename_nearmisslistno_nearmiss_nearmissno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nearmiss",
            name="safetyIndicater",
        ),
        migrations.RemoveField(
            model_name="nearmiss",
            name="totalOfNearMiss",
        ),
        migrations.AlterField(
            model_name="nearmiss",
            name="nearMissNo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="nearMissNo"
            ),
        ),
        migrations.CreateModel(
            name="ActionItemList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actionItems",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="actionItems"
                    ),
                ),
                (
                    "solvedActionItems",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="solvedActionItems",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actionItemList_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actionItemList_companyName",
                        to="accounts.companyname",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action Item List",
                "verbose_name_plural": "Action Item List",
                "ordering": ("-companyCode",),
            },
        ),
        migrations.CreateModel(
            name="SafetyIndicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "safetyIndicators",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="safetyIndicators",
                    ),
                ),
                (
                    "totalOfNearMiss",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="totalOfNearMiss"
                    ),
                ),
                (
                    "rateOflevelA",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="totalOfNearMiss"
                    ),
                ),
                (
                    "rateOfActionItems",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="totalOfNearMiss"
                    ),
                ),
                (
                    "ActionItems",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safetyIndicators_actionItems",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safetyIndicators_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safetyIndicators_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "solvedActionItems",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safetyIndicators_solvedActionItems",
                        to="accounts.companycode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safety Indicators",
                "verbose_name_plural": "Safety Indicators",
                "ordering": ("-companyCode",),
            },
        ),
    ]
