# Generated by Django 5.0.1 on 2024-03-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_companyname_options_alter_customuser_options"),
        ("nearMiss", "0003_nearmiss_companyname_alter_nearmiss_companycode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nearmiss",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearMiss_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="nearmiss",
            name="companyName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearMiss_companyName",
                to="accounts.companyname",
            ),
        ),
    ]
