# Generated by Django 5.0.1 on 2024-04-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0003_remove_nearmiss_safetyindicater_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safetyindicators",
            name="ActionItems",
        ),
        migrations.AlterField(
            model_name="safetyindicators",
            name="solvedActionItems",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="solvedActionItems"
            ),
        ),
        migrations.DeleteModel(
            name="ActionItemList",
        ),
        migrations.AddField(
            model_name="safetyindicators",
            name="actionItems",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="actionItems"
            ),
        ),
    ]
