# Generated by Django 5.0.1 on 2024-02-28 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0003_alter_nearmiss_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="nearmiss",
            name="totalOfNearMiss",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
