# Generated by Django 5.0.1 on 2024-04-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0004_remove_safetyindicators_actionitems_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safetyindicators",
            name="actionItems",
        ),
        migrations.RemoveField(
            model_name="safetyindicators",
            name="solvedActionItems",
        ),
        migrations.AddField(
            model_name="nearmiss",
            name="actionItems",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="actionItems"
            ),
        ),
        migrations.AddField(
            model_name="nearmiss",
            name="solvedActionItems",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="solvedActionItems"
            ),
        ),
        migrations.AddField(
            model_name="safetyindicators",
            name="countOfActionItems",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="countOfActionItems"
            ),
        ),
        migrations.AddField(
            model_name="safetyindicators",
            name="countOfSolvedActionItems",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="countOfSolvedActionItems",
            ),
        ),
        migrations.AddField(
            model_name="safetyindicators",
            name="dangerArea",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="dangerArea"
            ),
        ),
        migrations.AddField(
            model_name="safetyindicators",
            name="safetyIndicatorsWorld",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="safetyIndicatorsWorld",
            ),
        ),
    ]
