# Generated by Django 5.0.1 on 2024-04-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0006_alter_nearmiss_solvedactionitems"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetyindicators",
            name="countOfLevelA",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="countOfLevelA"
            ),
        ),
        migrations.AlterField(
            model_name="safetyindicators",
            name="rateOfActionItems",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="rateOfActionItems"
            ),
        ),
        migrations.AlterField(
            model_name="safetyindicators",
            name="rateOflevelA",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="rateOflevelA"
            ),
        ),
    ]
