# Generated by Django 5.0.1 on 2024-04-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0007_safetyindicators_countoflevela_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safetyindicators",
            name="safetyIndicatorsWorld",
        ),
    ]
