# Generated by Django 4.2.6 on 2024-04-08 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("nearMiss", "0008_remove_safetyindicators_safetyindicatorsworld"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendSafetyIndicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "years5Ago",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="years5Ago"
                    ),
                ),
                (
                    "years4Ago",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="years4Ago"
                    ),
                ),
                (
                    "years3Ago",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="years3Ago"
                    ),
                ),
                (
                    "years2Ago",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="years2Ago"
                    ),
                ),
                (
                    "years1Ago",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="years1Ago"
                    ),
                ),
                (
                    "thisYear",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="thisYear"
                    ),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trendSafetyIndicators_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trendSafetyIndicators_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "safetyIndicators",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trendSafetyIndicators_companyName",
                        to="nearMiss.safetyindicators",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trend Safety Indicators",
                "verbose_name_plural": "Trend Safety Indicators",
                "ordering": ("companyCode",),
            },
        ),
    ]
