# Generated by Django 5.0.1 on 2024-04-09 08:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0009_trendsafetyindicators"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trendsafetyindicators",
            name="thisYear",
        ),
        migrations.RemoveField(
            model_name="trendsafetyindicators",
            name="years1Ago",
        ),
        migrations.RemoveField(
            model_name="trendsafetyindicators",
            name="years2Ago",
        ),
        migrations.RemoveField(
            model_name="trendsafetyindicators",
            name="years3Ago",
        ),
        migrations.RemoveField(
            model_name="trendsafetyindicators",
            name="years4Ago",
        ),
        migrations.RemoveField(
            model_name="trendsafetyindicators",
            name="years5Ago",
        ),
        migrations.AddField(
            model_name="trendsafetyindicators",
            name="lastUpdateDay",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="lastUpdateDay",
            ),
        ),
    ]
