# Generated by Django 5.0.1 on 2024-07-09 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nearMiss", "0010_remove_trendsafetyindicators_thisyear_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nearmiss",
            name="email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nearMiss_email",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
