# Generated by Django 5.0.1 on 2024-08-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
