# Generated by Django 5.0.1 on 2024-08-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="testNo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
