# Generated by Django 5.0.1 on 2024-08-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_product_testno_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="testNo",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
