# Generated by Django 5.0.1 on 2024-08-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0004_alter_product_testno"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("testNo", None), _negated=True),
                fields=("testNo",),
                name="unique_test_no",
            ),
        ),
    ]
