# Generated by Django 5.0.1 on 2024-08-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0006_remove_product_unique_test_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="GanttTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
    ]
