# Generated by Django 5.0.1 on 2024-10-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0008_category_subcategory_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("background_color", models.CharField(default="#3788d8", max_length=7)),
                ("border_color", models.CharField(default="#3788d8", max_length=7)),
            ],
        ),
    ]
