# Generated by Django 5.0.1 on 2024-03-11 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_companyname_options_alter_customuser_options"),
        ("sustainability", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="co2",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="co2_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="compressedair",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comAir_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="electricityusage",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elec_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="exhaustgas",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exhaustGas_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="purewater",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pureWater_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="stm",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stm_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="wellwater",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wellWater_companyCode",
                to="accounts.companycode",
            ),
        ),
        migrations.AlterField(
            model_name="wwt",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wwt_companyCode",
                to="accounts.companycode",
            ),
        ),
    ]
