# Generated by Django 5.0.1 on 2024-03-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sustainability", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="co2",
            options={
                "ordering": ("date",),
                "verbose_name": "Co2 list",
                "verbose_name_plural": "Co2 List",
            },
        ),
        migrations.AlterModelOptions(
            name="compressedair",
            options={
                "ordering": ("date",),
                "verbose_name": "CompAir list",
                "verbose_name_plural": "CompAir List",
            },
        ),
        migrations.AlterModelOptions(
            name="electricityusage",
            options={
                "ordering": ("date",),
                "verbose_name": "Elec list",
                "verbose_name_plural": "Elec List",
            },
        ),
        migrations.AlterModelOptions(
            name="exhaustgas",
            options={
                "ordering": ("date",),
                "verbose_name": "exhaustGas list",
                "verbose_name_plural": "exhaustGas List",
            },
        ),
        migrations.AlterModelOptions(
            name="purewater",
            options={
                "ordering": ("date",),
                "verbose_name": "pureWater list",
                "verbose_name_plural": "pureWater List",
            },
        ),
        migrations.AlterModelOptions(
            name="stm",
            options={
                "ordering": ("date",),
                "verbose_name": "Stm list",
                "verbose_name_plural": "Stm List",
            },
        ),
        migrations.AlterModelOptions(
            name="wellwater",
            options={
                "ordering": ("date",),
                "verbose_name": "wellWater list",
                "verbose_name_plural": "wellWater List",
            },
        ),
        migrations.AlterModelOptions(
            name="wwt",
            options={
                "ordering": ("date",),
                "verbose_name": "wwt list",
                "verbose_name_plural": "wwt List",
            },
        ),
    ]
