# Generated by Django 5.0.1 on 2024-02-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sustainability", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectricityUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("plant", models.IntegerField(default=0, verbose_name="plant")),
                ("date", models.IntegerField(default=0, verbose_name="date")),
                ("cost", models.IntegerField(default=0, verbose_name="cost")),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StmList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("plant", models.IntegerField(default=0, verbose_name="plant")),
                ("date", models.IntegerField(default=0, verbose_name="date")),
                ("cost", models.IntegerField(default=0, verbose_name="cost")),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
