# Generated by Django 5.0.1 on 2024-03-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sustainability", "0002_co2_company_compressedair_company_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="co2",
            old_name="company",
            new_name="companyCode",
        ),
        migrations.RenameField(
            model_name="compressedair",
            old_name="company",
            new_name="companyCode",
        ),
        migrations.RenameField(
            model_name="electricityusage",
            old_name="company",
            new_name="companyCode",
        ),
        migrations.RenameField(
            model_name="exhaustgas",
            old_name="company",
            new_name="companyCode",
        ),
        migrations.RenameField(
            model_name="purewater",
            old_name="company",
            new_name="companyCode",
        ),
        migrations.RenameField(
            model_name="stm",
            old_name="company",
            new_name="companyCode",
        ),
        migrations.RenameField(
            model_name="wellwater",
            old_name="company",
            new_name="companyCode",
        ),
        migrations.RenameField(
            model_name="wwt",
            old_name="company",
            new_name="companyCode",
        ),
    ]
