# Generated by Django 5.0.1 on 2024-02-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sustainability", "0002_electricityusage_stmlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompressedAir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("plant", models.IntegerField(default=0, verbose_name="plant")),
                ("date", models.IntegerField(default=0, verbose_name="date")),
                (
                    "compAirCost",
                    models.IntegerField(default=0, verbose_name="compAirCost"),
                ),
                ("createdDay", models.DateTimeField(auto_now_add=True)),
                ("updateDay", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="co2list",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="electricityusage",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="stmlist",
            name="cost",
        ),
        migrations.AddField(
            model_name="co2list",
            name="co2Cost",
            field=models.IntegerField(default=0, verbose_name="co2Cost"),
        ),
        migrations.AddField(
            model_name="electricityusage",
            name="elecCost",
            field=models.IntegerField(default=0, verbose_name="elecCost"),
        ),
        migrations.AddField(
            model_name="stmlist",
            name="stmCost",
            field=models.IntegerField(default=0, verbose_name="stmCost"),
        ),
    ]
