# Generated by Django 5.0.1 on 2024-03-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sustainability",
            "0003_alter_co2_co2cost_alter_compressedair_compaircost_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="co2",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="compressedair",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="electricityusage",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="exhaustgas",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="purewater",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="stm",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="wellwater",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="wwt",
            name="slug",
        ),
    ]
