# Generated by Django 5.0.1 on 2024-03-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sustainability", "0003_rename_company_co2_companycode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhaustgas",
            name="exhaustGasCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=12,
                null=True,
                verbose_name="exhaustGasCost",
            ),
        ),
    ]
