# Generated by Django 5.0.1 on 2024-02-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sustainability", "0007_exhaustgas"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Co2List",
            new_name="Co2",
        ),
        migrations.RenameModel(
            old_name="StmList",
            new_name="Stm",
        ),
    ]
