# Generated by Django 5.0.1 on 2024-02-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sustainability", "0008_rename_co2list_co2_rename_stmlist_stm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhaustgas",
            name="exhaustGasCost",
        ),
    ]
