# Generated by Django 5.0.1 on 2024-03-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0003_remove_function_companycode_and_more"),
        ("taskList", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklist",
            name="function",
        ),
        migrations.AddField(
            model_name="tasklist",
            name="machineName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taskList_function",
                to="ceList.machine",
            ),
        ),
    ]
