# Generated by Django 5.0.1 on 2024-03-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("ceList", "0003_typeofpm_celist_celist_id_alter_celist_bomcode_and_more"),
        ("taskList", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklist",
            name="taskOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklist",
            name="typeOfMaintenance",
        ),
        migrations.AddField(
            model_name="tasklist",
            name="typeOfPM",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="taskList_typeOfPM",
                to="ceList.typeofpm",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taskList_companyCode",
                to="accounts.company",
            ),
        ),
    ]
