# Generated by Django 5.0.1 on 2024-03-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0002_remove_tasklist_taskofpm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="constructionPeriod",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="constructionPeriod"
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="periodOfPM",
            field=models.IntegerField(blank=True, null=True, verbose_name="periodOfPM"),
        ),
    ]
