# Generated by Django 5.0.1 on 2024-03-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0002_tasklist_delete_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasklist",
            options={
                "ordering": ("taskCode",),
                "verbose_name": "Task List",
                "verbose_name_plural": "Task List",
            },
        ),
    ]
