# Generated by Django 5.0.1 on 2024-03-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0008_rename_bomno_celist_bomcode_and_more"),
        ("taskList", "0003_alter_tasklist_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipment_taskList",
                to="ceList.celist",
            ),
        ),
        migrations.AddField(
            model_name="tasklist",
            name="function",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_taskList",
                to="ceList.celist",
            ),
        ),
        migrations.AddField(
            model_name="tasklist",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plant_taskList",
                to="ceList.celist",
            ),
        ),
    ]
