# Generated by Django 5.0.1 on 2024-03-09 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0004_tasklist_equipment_tasklist_function_tasklist_plant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklist",
            name="slug",
        ),
    ]
