# Generated by Django 5.0.1 on 2024-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0004_alter_tasklist_companycode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="laborCostOfPM",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="laborCostOfPM",
            ),
        ),
    ]
