# Generated by Django 5.0.1 on 2024-03-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0005_remove_tasklist_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="thisYear",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="thisYear"
            ),
        ),
    ]
