# Generated by Django 5.0.1 on 2024-03-20 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("taskList", "0006_remove_tasklist_equipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taskList_plant",
                to="accounts.plant",
            ),
        ),
    ]
