# Generated by Django 5.0.1 on 2024-03-09 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0008_rename_bomno_celist_bomcode_and_more"),
        ("taskList", "0006_alter_tasklist_thisyear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipment_taskList",
                to="ceList.celist",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="function",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="function_taskList",
                to="ceList.celist",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="plant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plant_taskList",
                to="ceList.celist",
            ),
        ),
    ]
