# Generated by Django 5.0.1 on 2024-03-20 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceList", "0007_alter_celist_machinename_and_more"),
        ("taskList", "0007_tasklist_plant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taskList_equipment",
                to="ceList.equipment",
            ),
        ),
        migrations.AddField(
            model_name="tasklist",
            name="machineName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taskList_machineName",
                to="ceList.celist",
            ),
        ),
        migrations.AddField(
            model_name="tasklist",
            name="typeOfPM",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="typeOfPM"
            ),
        ),
    ]
