# Generated by Django 5.0.1 on 2024-03-20 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("ceList", "0007_alter_celist_machinename_and_more"),
        ("junctionTable", "0004_remove_masterdatatable_celist_id_and_more"),
        ("taskList", "0008_tasklist_equipment_tasklist_machinename_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskListPM02",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taskCode",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskCode"
                    ),
                ),
                (
                    "taskName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskName"
                    ),
                ),
                (
                    "laborCostOfPM",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="laborCostOfPM",
                    ),
                ),
                (
                    "countOfPM",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="countOfPM"
                    ),
                ),
                (
                    "latestPM",
                    models.DateField(blank=True, null=True, verbose_name="latestPM"),
                ),
                (
                    "periodOfPM",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="periodOfPM"
                    ),
                ),
                (
                    "constructionPeriod",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="constructionPeriod"
                    ),
                ),
                (
                    "nextEventDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="nextEventDate"
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="situation"
                    ),
                ),
                (
                    "thisYear10ago",
                    models.BooleanField(default=False, verbose_name="thisYear10ago"),
                ),
                (
                    "thisYear9ago",
                    models.BooleanField(default=False, verbose_name="thisYear9ago"),
                ),
                (
                    "thisYear8ago",
                    models.BooleanField(default=False, verbose_name="thisYear8ago"),
                ),
                (
                    "thisYear7ago",
                    models.BooleanField(default=False, verbose_name="thisYear7ago"),
                ),
                (
                    "thisYear6ago",
                    models.BooleanField(default=False, verbose_name="thisYear6ago"),
                ),
                (
                    "thisYear5ago",
                    models.BooleanField(default=False, verbose_name="thisYear5ago"),
                ),
                (
                    "thisYear4ago",
                    models.BooleanField(default=False, verbose_name="thisYear4ago"),
                ),
                (
                    "thisYear3ago",
                    models.BooleanField(default=False, verbose_name="thisYear3ago"),
                ),
                (
                    "thisYear2ago",
                    models.BooleanField(default=False, verbose_name="thisYear2ago"),
                ),
                (
                    "thisYear1ago",
                    models.BooleanField(default=False, verbose_name="thisYear1ago"),
                ),
                (
                    "thisYear",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="thisYear"
                    ),
                ),
                (
                    "thisYear1later",
                    models.BooleanField(default=False, verbose_name="thisYear1later"),
                ),
                (
                    "thisYear2later",
                    models.BooleanField(default=False, verbose_name="thisYear2later"),
                ),
                (
                    "thisYear3later",
                    models.BooleanField(default=False, verbose_name="thisYear3later"),
                ),
                (
                    "thisYear4later",
                    models.BooleanField(default=False, verbose_name="thisYear4later"),
                ),
                (
                    "thisYear5later",
                    models.BooleanField(default=False, verbose_name="thisYear5later"),
                ),
                (
                    "thisYear6later",
                    models.BooleanField(default=False, verbose_name="thisYear6later"),
                ),
                (
                    "thisYear7later",
                    models.BooleanField(default=False, verbose_name="thisYear7later"),
                ),
                (
                    "thisYear8later",
                    models.BooleanField(default=False, verbose_name="thisYear8later"),
                ),
                (
                    "thisYear9later",
                    models.BooleanField(default=False, verbose_name="thisYear9later"),
                ),
                (
                    "thisYear10later",
                    models.BooleanField(default=False, verbose_name="thisYear10later"),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM02_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM02_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM02_equipment",
                        to="ceList.equipment",
                    ),
                ),
                (
                    "machineName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM02_machineName",
                        to="ceList.celist",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM02_plant",
                        to="accounts.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task List Pm02",
                "verbose_name_plural": "Task List Pm02",
                "ordering": ("taskCode",),
            },
        ),
        migrations.CreateModel(
            name="TaskListPM03",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taskCode",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskCode"
                    ),
                ),
                (
                    "taskName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskName"
                    ),
                ),
                (
                    "laborCostOfPM",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="laborCostOfPM",
                    ),
                ),
                (
                    "countOfPM",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="countOfPM"
                    ),
                ),
                (
                    "latestPM",
                    models.DateField(blank=True, null=True, verbose_name="latestPM"),
                ),
                (
                    "periodOfPM",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="periodOfPM"
                    ),
                ),
                (
                    "constructionPeriod",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="constructionPeriod"
                    ),
                ),
                (
                    "nextEventDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="nextEventDate"
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="situation"
                    ),
                ),
                (
                    "thisYear10ago",
                    models.BooleanField(default=False, verbose_name="thisYear10ago"),
                ),
                (
                    "thisYear9ago",
                    models.BooleanField(default=False, verbose_name="thisYear9ago"),
                ),
                (
                    "thisYear8ago",
                    models.BooleanField(default=False, verbose_name="thisYear8ago"),
                ),
                (
                    "thisYear7ago",
                    models.BooleanField(default=False, verbose_name="thisYear7ago"),
                ),
                (
                    "thisYear6ago",
                    models.BooleanField(default=False, verbose_name="thisYear6ago"),
                ),
                (
                    "thisYear5ago",
                    models.BooleanField(default=False, verbose_name="thisYear5ago"),
                ),
                (
                    "thisYear4ago",
                    models.BooleanField(default=False, verbose_name="thisYear4ago"),
                ),
                (
                    "thisYear3ago",
                    models.BooleanField(default=False, verbose_name="thisYear3ago"),
                ),
                (
                    "thisYear2ago",
                    models.BooleanField(default=False, verbose_name="thisYear2ago"),
                ),
                (
                    "thisYear1ago",
                    models.BooleanField(default=False, verbose_name="thisYear1ago"),
                ),
                (
                    "thisYear",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="thisYear"
                    ),
                ),
                (
                    "thisYear1later",
                    models.BooleanField(default=False, verbose_name="thisYear1later"),
                ),
                (
                    "thisYear2later",
                    models.BooleanField(default=False, verbose_name="thisYear2later"),
                ),
                (
                    "thisYear3later",
                    models.BooleanField(default=False, verbose_name="thisYear3later"),
                ),
                (
                    "thisYear4later",
                    models.BooleanField(default=False, verbose_name="thisYear4later"),
                ),
                (
                    "thisYear5later",
                    models.BooleanField(default=False, verbose_name="thisYear5later"),
                ),
                (
                    "thisYear6later",
                    models.BooleanField(default=False, verbose_name="thisYear6later"),
                ),
                (
                    "thisYear7later",
                    models.BooleanField(default=False, verbose_name="thisYear7later"),
                ),
                (
                    "thisYear8later",
                    models.BooleanField(default=False, verbose_name="thisYear8later"),
                ),
                (
                    "thisYear9later",
                    models.BooleanField(default=False, verbose_name="thisYear9later"),
                ),
                (
                    "thisYear10later",
                    models.BooleanField(default=False, verbose_name="thisYear10later"),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM03_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM03_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM03_equipment",
                        to="ceList.equipment",
                    ),
                ),
                (
                    "machineName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM03_machineName",
                        to="ceList.celist",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM03_plant",
                        to="accounts.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task List Pm03",
                "verbose_name_plural": "Task List Pm03",
                "ordering": ("taskCode",),
            },
        ),
        migrations.CreateModel(
            name="TaskListPM04",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taskCode",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskCode"
                    ),
                ),
                (
                    "taskName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskName"
                    ),
                ),
                (
                    "laborCostOfPM",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="laborCostOfPM",
                    ),
                ),
                (
                    "countOfPM",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="countOfPM"
                    ),
                ),
                (
                    "latestPM",
                    models.DateField(blank=True, null=True, verbose_name="latestPM"),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM04_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM4_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM04_equipment",
                        to="ceList.equipment",
                    ),
                ),
                (
                    "machineName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM04_machineName",
                        to="ceList.celist",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM04_plant",
                        to="accounts.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task List Pm04",
                "verbose_name_plural": "Task List Pm04",
                "ordering": ("taskCode",),
            },
        ),
        migrations.CreateModel(
            name="TaskListPM05",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taskCode",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskCode"
                    ),
                ),
                (
                    "taskName",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="taskName"
                    ),
                ),
                (
                    "laborCostOfPM",
                    models.DecimalField(
                        blank=True,
                        decimal_places=5,
                        default=0.0,
                        max_digits=10,
                        null=True,
                        verbose_name="laborCostOfPM",
                    ),
                ),
                (
                    "countOfPM",
                    models.PositiveSmallIntegerField(
                        blank=True, default=0, null=True, verbose_name="countOfPM"
                    ),
                ),
                (
                    "latestPM",
                    models.DateField(blank=True, null=True, verbose_name="latestPM"),
                ),
                (
                    "periodOfPM",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="periodOfPM"
                    ),
                ),
                (
                    "constructionPeriod",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="constructionPeriod"
                    ),
                ),
                (
                    "nextEventDate",
                    models.DateField(
                        blank=True, null=True, verbose_name="nextEventDate"
                    ),
                ),
                (
                    "situation",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="situation"
                    ),
                ),
                (
                    "thisYear10ago",
                    models.BooleanField(default=False, verbose_name="thisYear10ago"),
                ),
                (
                    "thisYear9ago",
                    models.BooleanField(default=False, verbose_name="thisYear9ago"),
                ),
                (
                    "thisYear8ago",
                    models.BooleanField(default=False, verbose_name="thisYear8ago"),
                ),
                (
                    "thisYear7ago",
                    models.BooleanField(default=False, verbose_name="thisYear7ago"),
                ),
                (
                    "thisYear6ago",
                    models.BooleanField(default=False, verbose_name="thisYear6ago"),
                ),
                (
                    "thisYear5ago",
                    models.BooleanField(default=False, verbose_name="thisYear5ago"),
                ),
                (
                    "thisYear4ago",
                    models.BooleanField(default=False, verbose_name="thisYear4ago"),
                ),
                (
                    "thisYear3ago",
                    models.BooleanField(default=False, verbose_name="thisYear3ago"),
                ),
                (
                    "thisYear2ago",
                    models.BooleanField(default=False, verbose_name="thisYear2ago"),
                ),
                (
                    "thisYear1ago",
                    models.BooleanField(default=False, verbose_name="thisYear1ago"),
                ),
                (
                    "thisYear",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="thisYear"
                    ),
                ),
                (
                    "thisYear1later",
                    models.BooleanField(default=False, verbose_name="thisYear1later"),
                ),
                (
                    "thisYear2later",
                    models.BooleanField(default=False, verbose_name="thisYear2later"),
                ),
                (
                    "thisYear3later",
                    models.BooleanField(default=False, verbose_name="thisYear3later"),
                ),
                (
                    "thisYear4later",
                    models.BooleanField(default=False, verbose_name="thisYear4later"),
                ),
                (
                    "thisYear5later",
                    models.BooleanField(default=False, verbose_name="thisYear5later"),
                ),
                (
                    "thisYear6later",
                    models.BooleanField(default=False, verbose_name="thisYear6later"),
                ),
                (
                    "thisYear7later",
                    models.BooleanField(default=False, verbose_name="thisYear7later"),
                ),
                (
                    "thisYear8later",
                    models.BooleanField(default=False, verbose_name="thisYear8later"),
                ),
                (
                    "thisYear9later",
                    models.BooleanField(default=False, verbose_name="thisYear9later"),
                ),
                (
                    "thisYear10later",
                    models.BooleanField(default=False, verbose_name="thisYear10later"),
                ),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM05_companyCode",
                        to="accounts.companycode",
                    ),
                ),
                (
                    "companyName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM05_companyName",
                        to="accounts.companyname",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM05_equipment",
                        to="ceList.equipment",
                    ),
                ),
                (
                    "machineName",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM05_machineName",
                        to="ceList.celist",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taskListPM05_plant",
                        to="accounts.plant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task List Pm05",
                "verbose_name_plural": "Task List Pm05",
                "ordering": ("taskCode",),
            },
        ),
        migrations.DeleteModel(
            name="TaskList",
        ),
    ]
