# Generated by Django 5.0.1 on 2024-07-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taskList",
            "0009_alter_tasklist_options_remove_tasklist_companyname_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklistppm02",
            name="pM02Content",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="pM02Content"
            ),
        ),
    ]
