# Generated by Django 5.0.1 on 2024-03-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "taskList",
            "0009_tasklistpm02_tasklistpm03_tasklistpm04_tasklistpm05_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklistpm04",
            name="constructionPeriod",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="constructionPeriod"
            ),
        ),
    ]
