# Generated by Django 5.0.1 on 2024-07-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0010_tasklistppm02_pm02content"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklistppm02",
            name="maintenanceCategory",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="maintenanceCategory",
            ),
        ),
    ]
