# Generated by Django 5.0.1 on 2024-07-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0011_tasklistppm02_maintenancecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklistppm03",
            name="maintenanceCategory",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="maintenanceCategory",
            ),
        ),
        migrations.AddField(
            model_name="tasklistppm03",
            name="pM03Content",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="pM03Content"
            ),
        ),
        migrations.AlterField(
            model_name="tasklistppm02",
            name="laborCostOfPPM02",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default=0.0,
                max_digits=20,
                null=True,
                verbose_name="laborCostOfPPM02",
            ),
        ),
        migrations.AlterField(
            model_name="tasklistppm03",
            name="laborCostOfPPM03",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default=0.0,
                max_digits=20,
                null=True,
                verbose_name="laborCostOfPPM03",
            ),
        ),
    ]
