# Generated by Django 5.0.1 on 2024-03-25 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_plant"),
        ("taskList", "0011_typicaltasklist_alter_tasklistpm02_machinename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist",
            name="totalCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="totalCost",
            ),
        ),
        migrations.AddField(
            model_name="typicaltasklist",
            name="companyCode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typicalTaskList_companyCode",
                to="accounts.companycode",
            ),
        ),
    ]
