# Generated by Django 5.0.1 on 2024-03-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0012_tasklist_totalcost_typicaltasklist_companycode"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist",
            name="taskListNo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="taskListNo"
            ),
        ),
    ]
