# Generated by Django 5.0.1 on 2024-07-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0012_tasklistppm03_maintenancecategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklistppm02",
            name="ceListNo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ceListNo"
            ),
        ),
        migrations.AddField(
            model_name="tasklistppm03",
            name="ceListNo",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ceListNo"
            ),
        ),
    ]
