# Generated by Django 5.0.1 on 2024-08-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0013_tasklistppm02_celistno_tasklistppm03_celistno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="bomCode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="bomCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="equipment",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="machineName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="multiTasking",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="plant",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="typicalConstPeriod",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="typicalLatestDate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="typicalNextEventDate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="typicalSituation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="typicalTaskCost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="typicalTaskName",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
