# Generated by Django 5.0.1 on 2024-03-25 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0014_remove_tasklist_bomcodecost_tasklist_bomcost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklist",
            name="typicalTask",
        ),
        migrations.RemoveField(
            model_name="typicaltasklist",
            name="typicalTask",
        ),
        migrations.AddField(
            model_name="tasklist",
            name="typicalTaskName",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taskList_typicalTaskName",
                to="taskList.typicaltasklist",
            ),
        ),
        migrations.AddField(
            model_name="typicaltasklist",
            name="typicalTaskName",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="typicalTaskName"
            ),
        ),
    ]
