# Generated by Django 5.0.1 on 2024-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0014_alter_tasklist_bomcode_alter_tasklist_bomcost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("pmType", models.CharField(max_length=50)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
            ],
        ),
    ]
