# Generated by Django 5.0.1 on 2024-03-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0015_remove_tasklist_typicaltask_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklist",
            name="thisYear",
            field=models.BooleanField(default=False, verbose_name="thisYear"),
        ),
    ]
