# Generated by Django 5.0.1 on 2024-09-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0015_schedule"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
