# Generated by Django 5.0.1 on 2024-09-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0016_delete_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist",
            name="pmType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="pmType"
            ),
        ),
    ]
