# Generated by Django 5.0.1 on 2024-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0016_alter_tasklist_thisyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="typicaltasklist",
            name="typicalSituation",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="typicalSituation"
            ),
        ),
    ]
