# Generated by Django 5.0.1 on 2024-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0017_typicaltasklist_typicalsituation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklistpm02",
            name="countOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm02",
            name="laborCostOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm02",
            name="latestPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm02",
            name="periodOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm03",
            name="countOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm03",
            name="laborCostOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm03",
            name="latestPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm03",
            name="periodOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm04",
            name="countOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm04",
            name="laborCostOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm04",
            name="latestPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm05",
            name="countOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm05",
            name="laborCostOfPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm05",
            name="latestPM",
        ),
        migrations.RemoveField(
            model_name="tasklistpm05",
            name="periodOfPM",
        ),
        migrations.AddField(
            model_name="tasklistpm02",
            name="countOfPM02",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM02"
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm02",
            name="laborCostOfPM02",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="laborCostOfPM02",
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm02",
            name="latestPM02",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM02"),
        ),
        migrations.AddField(
            model_name="tasklistpm02",
            name="periodOfPM02",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="periodOfPM02"
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm03",
            name="countOfPM03",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM03"
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm03",
            name="laborCostOfPM03",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="laborCostOfPM03",
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm03",
            name="latestPM03",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM03"),
        ),
        migrations.AddField(
            model_name="tasklistpm03",
            name="periodOfPM03",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="periodOfPM03"
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm04",
            name="countOfPM04",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM04"
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm04",
            name="laborCostOfPM04",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="laborCostOfPM04",
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm04",
            name="latestPM04",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM04"),
        ),
        migrations.AddField(
            model_name="tasklistpm05",
            name="countOfPM05",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="countOfPM05"
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm05",
            name="laborCostOfPM05",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="laborCostOfPM05",
            ),
        ),
        migrations.AddField(
            model_name="tasklistpm05",
            name="latestPM05",
            field=models.DateField(blank=True, null=True, verbose_name="latestPM05"),
        ),
        migrations.AddField(
            model_name="tasklistpm05",
            name="periodOfPM05",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="periodOfPM05"
            ),
        ),
    ]
