# Generated by Django 5.0.1 on 2024-09-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0017_tasklist_pmtype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasklist",
            old_name="multiTasking",
            new_name="latestEventDate",
        ),
        migrations.RenameField(
            model_name="tasklist",
            old_name="typicalConstPeriod",
            new_name="nextEventDate",
        ),
        migrations.RenameField(
            model_name="tasklist",
            old_name="typicalLatestDate",
            new_name="situation",
        ),
        migrations.RenameField(
            model_name="tasklist",
            old_name="typicalTaskCost",
            new_name="taskLaborCost",
        ),
        migrations.RenameField(
            model_name="tasklist",
            old_name="typicalNextEventDate",
            new_name="taskName",
        ),
        migrations.RenameField(
            model_name="tasklist",
            old_name="typicalSituation",
            new_name="taskPeriod",
        ),
        migrations.RemoveField(
            model_name="tasklist",
            name="typicalTaskName",
        ),
        migrations.AddField(
            model_name="tasklist",
            name="maintenanceType",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="maintenanceType"
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="pmType",
            field=models.CharField(
                blank=True,
                default="PM01",
                max_length=100,
                null=True,
                verbose_name="pmType",
            ),
        ),
        migrations.AlterField(
            model_name="tasklist",
            name="totalCost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="totalCost",
            ),
        ),
    ]
