# Generated by Django 5.0.1 on 2024-04-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskList", "0018_remove_tasklistpm02_countofpm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklistpm02",
            name="thisYear",
            field=models.BooleanField(default=False, verbose_name="thisYear"),
        ),
        migrations.AlterField(
            model_name="tasklistpm03",
            name="thisYear",
            field=models.BooleanField(default=False, verbose_name="thisYear"),
        ),
        migrations.AlterField(
            model_name="tasklistpm05",
            name="thisYear",
            field=models.BooleanField(default=False, verbose_name="thisYear"),
        ),
    ]
