# Generated by Django 5.0.1 on 2024-04-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("junctionTable", "0013_alter_masterdatatable_countofpm02_and_more"),
        ("taskList", "0020_remove_tasklistpm02_companycode_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskListPM02",
        ),
        migrations.DeleteModel(
            name="TaskListPM03",
        ),
        migrations.DeleteModel(
            name="TaskListPM04",
        ),
        migrations.DeleteModel(
            name="TaskListPM05",
        ),
    ]
