# Generated by Django 5.0.1 on 2024-09-11 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskListNo", models.CharField(max_length=255)),
                ("typicalTaskName", models.CharField(max_length=255)),
                ("plant", models.CharField(max_length=255)),
                ("equipment", models.CharField(max_length=255)),
                ("machineName", models.CharField(max_length=255)),
                ("typicalLatestDate", models.DateField()),
                ("multiTasking", models.BooleanField()),
                ("totalCost", models.FloatField()),
                ("taskOfPeriod", models.IntegerField()),
                (
                    "typicalNextEventDate",
                    models.CharField(editable=False, max_length=255),
                ),
                ("typicalSituation", models.CharField(editable=False, max_length=255)),
                ("thisYear", models.BooleanField(editable=False)),
                ("thisYear1Later", models.BooleanField(editable=False)),
                ("thisYear2Later", models.BooleanField(editable=False)),
                ("thisYear3Later", models.BooleanField(editable=False)),
                ("thisYear4Later", models.BooleanField(editable=False)),
                ("thisYear5Later", models.BooleanField(editable=False)),
                ("thisYear6Later", models.BooleanField(editable=False)),
                ("thisYear7Later", models.BooleanField(editable=False)),
                ("thisYear8Later", models.BooleanField(editable=False)),
                ("thisYear9Later", models.BooleanField(editable=False)),
                ("thisYear10Later", models.BooleanField(editable=False)),
                (
                    "companyCode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="simulation_companyCode",
                        to="accounts.companycode",
                    ),
                ),
            ],
        ),
    ]
