# Generated by Django 5.0.1 on 2024-10-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0003_remove_no1simulation_multitasking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="no1simulation",
            name="maintenanceType",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="no2simulation",
            name="maintenanceType",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="no3simulation",
            name="maintenanceType",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
